In [1]:
!pip install pandas numpy faker openpyxl

Requirement already satisfied: pandas in C:\Users\USER\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.2)
Requirement already satisfied: numpy in C:\Users\USER\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.4.4)
Collecting faker
  Downloading faker-40.36.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: openpyxl in C:\Users\USER\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.1.5)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\USER\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\USER\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: et-xmlfile in C:\Users\USER\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in C:\Users\USER\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading faker-40.36.0-py3-none-any.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.1 MB ? eta -:--:--
   ------------------------- -------------- 1.3/2.1 MB 4.4 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 3.8 MB/s  0:00:00
Installing collected packages: faker
Successfully installed faker-40.36.0

  WARNING: The script faker.exe is installed in 'C:\Users\USER\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: C:\Users\USER\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np
from faker import Faker

print("All libraries imported successfully!")

All libraries imported successfully!

In [3]:
import pandas as pd
import numpy as np
from faker import Faker
import random

# Initialize Faker
fake = Faker()

In [4]:
NUM_CUSTOMERS = 10000

In [5]:
uae_locations = [
    ("Dubai", "Dubai"),
    ("Abu Dhabi", "Abu Dhabi"),
    ("Sharjah", "Sharjah"),
    ("Ajman", "Ajman"),
    ("Ras Al Khaimah", "Ras Al Khaimah"),
    ("Fujairah", "Fujairah"),
    ("Umm Al Quwain", "Umm Al Quwain"),
    ("Al Ain", "Abu Dhabi")
]

In [11]:
customers = []

for i in range(1, NUM_CUSTOMERS + 1):

    city, emirate = random.choice(uae_locations)

    customers.append({
        "customer_id": f"C{i:05}",
        "customer_name": fake.name(),
        "gender": random.choice(["Male", "Female"]),
        "age": random.randint(18,70),
        "city": city,
        "emirate": emirate,
        "segment": random.choices(
            customer_segments,
            weights=[70,20,10]
        )[0],
        "loyalty_status": random.choices(
            loyalty_program,
            weights=[60,30,10]
        )[0],
        "email": fake.email(),
        "phone": fake.phone_number(),
        "join_date": fake.date_between(
            start_date="-5y",
            end_date="today"
        )
    })

In [12]:
customers_df = pd.DataFrame(customers)

customers_df.head()

,customer_id,customer_name,gender,age,city,emirate,segment,loyalty_status,email,phone,join_date
0,C00001,Jessica Long,Female,35,Fujairah,Fujairah,Home Office,Silver,jesseclark@example.net,001-242-462-4150,2024-11-30
1,C00002,Stephanie Smith,Male,42,Fujairah,Fujairah,Consumer,Gold,terri67@example.net,984.981.9065,2024-04-19
2,C00003,Michael Mora,Male,69,Sharjah,Sharjah,Consumer,Silver,vsanders@example.com,537.731.6463x890,2023-12-13
3,C00004,Kevin Bryan,Female,39,Dubai,Dubai,Consumer,Silver,ryanstone@example.org,865.241.4551,2025-06-25
4,C00005,Mathew Foley,Female,65,Umm Al Quwain,Umm Al Quwain,Consumer,Silver,cwood@example.com,288-223-6762x170,2022-08-30

In [13]:
customers_df.to_csv("customers.csv", index=False)

print("customers.csv created successfully!")

customers.csv created successfully!

In [9]:
customer_segments = [
    "Consumer",
    "Corporate",
    "Home Office"
]

In [10]:
loyalty_program = [
    "Silver",
    "Gold",
    "Platinum"
]

In [14]:
# ==========================================
# FreshMart UAE - Product Category Master
# ==========================================

product_categories = {
    "Fruits & Vegetables": [
        "Fresh Fruits",
        "Fresh Vegetables",
        "Herbs"
    ],

    "Dairy & Eggs": [
        "Milk",
        "Cheese",
        "Yogurt",
        "Butter",
        "Eggs"
    ],

    "Bakery": [
        "Bread",
        "Cakes",
        "Pastries"
    ],

    "Beverages": [
        "Water",
        "Soft Drinks",
        "Juices",
        "Tea",
        "Coffee",
        "Energy Drinks"
    ],

    "Snacks": [
        "Chips",
        "Biscuits",
        "Chocolates",
        "Nuts"
    ],

    "Frozen Foods": [
        "Frozen Vegetables",
        "Ice Cream",
        "Frozen Chicken"
    ],

    "Meat & Seafood": [
        "Chicken",
        "Beef",
        "Fish",
        "Seafood"
    ],

    "Pantry": [
        "Rice",
        "Pasta",
        "Flour",
        "Sugar",
        "Cooking Oil",
        "Spices"
    ],

    "Personal Care": [
        "Shampoo",
        "Soap",
        "Toothpaste",
        "Skincare"
    ],

    "Household": [
        "Tissue",
        "Garbage Bags",
        "Foil",
        "Storage Bags"
    ],

    "Cleaning Supplies": [
        "Detergent",
        "Floor Cleaner",
        "Dishwashing Liquid"
    ],

    "Baby Care": [
        "Diapers",
        "Baby Food",
        "Baby Wipes"
    ]
}

In [15]:
# ==========================================
# FreshMart UAE - Brand Master
# ==========================================

brand_master = {
    "Fruits & Vegetables": [
        "FreshMart",
        "Nature Fresh",
        "Green Farm"
    ],

    "Dairy & Eggs": [
        "Almarai",
        "Al Ain Farms",
        "Nadec",
        "FreshMart"
    ],

    "Bakery": [
        "FreshMart",
        "Modern Bakery",
        "L'usine"
    ],

    "Beverages": [
        "Coca-Cola",
        "Pepsi",
        "Lacnor",
        "Masafi",
        "FreshMart"
    ],

    "Snacks": [
        "Oreo",
        "Pringles",
        "KitKat",
        "FreshMart"
    ],

    "Frozen Foods": [
        "Americana",
        "FreshMart",
        "Al Kabeer"
    ],

    "Meat & Seafood": [
        "FreshMart",
        "Al Islami",
        "Sadia"
    ],

    "Pantry": [
        "FreshMart",
        "Noor",
        "Sunbulah"
    ],

    "Personal Care": [
        "Dove",
        "Pantene",
        "Colgate",
        "FreshMart"
    ],

    "Household": [
        "FreshMart",
        "Kleenex",
        "Glad"
    ],

    "Cleaning Supplies": [
        "FreshMart",
        "Dettol",
        "Persil",
        "Finish"
    ],

    "Baby Care": [
        "Pampers",
        "Johnson's",
        "FreshMart"
    ]
}

In [16]:
# ==========================================
# FreshMart UAE - Product Template Master
# Part 1 : Fruits & Vegetables
# ==========================================

product_templates = {
    "Fruits & Vegetables": {
        "Fresh Fruits": [
            "Bananas",
            "Apples",
            "Oranges",
            "Mangoes",
            "Grapes",
            "Strawberries",
            "Watermelon",
            "Pineapple",
            "Papaya",
            "Avocados"
        ],

        "Fresh Vegetables": [
            "Tomatoes",
            "Potatoes",
            "Onions",
            "Carrots",
            "Cucumbers",
            "Capsicum",
            "Broccoli",
            "Cauliflower",
            "Spinach",
            "Lettuce"
        ],

        "Herbs": [
            "Coriander",
            "Mint",
            "Parsley",
            "Basil",
            "Rosemary"
        ]
    }
}

In [17]:
# ==========================================
# FreshMart UAE - Product Template Master
# Part 2 : Dairy & Eggs
# ==========================================

product_templates["Dairy & Eggs"] = {

    "Milk": [
        "Full Cream Milk",
        "Low Fat Milk",
        "Skimmed Milk",
        "Fresh Milk",
        "Chocolate Milk"
    ],

    "Cheese": [
        "Cheddar Cheese",
        "Mozzarella Cheese",
        "Cream Cheese",
        "Feta Cheese",
        "Processed Cheese Slices"
    ],

    "Yogurt": [
        "Plain Yogurt",
        "Greek Yogurt",
        "Strawberry Yogurt",
        "Mango Yogurt",
        "Vanilla Yogurt"
    ],

    "Butter": [
        "Salted Butter",
        "Unsalted Butter",
        "Garlic Butter"
    ],

    "Eggs": [
        "White Eggs 6 Pack",
        "White Eggs 12 Pack",
        "Brown Eggs 6 Pack",
        "Brown Eggs 12 Pack",
        "Organic Eggs 6 Pack"
    ]
}

In [18]:
print(product_templates.keys())

dict_keys(['Fruits & Vegetables', 'Dairy & Eggs'])

In [19]:
# ==========================================
# FreshMart UAE - Product Template Master
# Part 3 : Bakery
# ==========================================

product_templates["Bakery"] = {

    "Bread": [
        "White Bread",
        "Whole Wheat Bread",
        "Multigrain Bread",
        "Garlic Bread",
        "Burger Buns",
        "Hot Dog Buns",
        "Dinner Rolls"
    ],

    "Cakes": [
        "Chocolate Cake",
        "Vanilla Cake",
        "Red Velvet Cake",
        "Black Forest Cake",
        "Cheesecake"
    ],

    "Pastries": [
        "Butter Croissant",
        "Chocolate Croissant",
        "Blueberry Muffin",
        "Chocolate Muffin",
        "Cinnamon Roll",
        "Danish Pastry"
    ]
}

In [20]:
# ==========================================
# FreshMart UAE - Product Template Master
# Part 4 : Beverages
# ==========================================

product_templates["Beverages"] = {

    "Water": [
        "Still Water",
        "Sparkling Water",
        "Mineral Water"
    ],

    "Soft Drinks": [
        "Cola",
        "Diet Cola",
        "Lemon Lime Soda",
        "Orange Soda",
        "Ginger Ale"
    ],

    "Juices": [
        "Orange Juice",
        "Apple Juice",
        "Mango Juice",
        "Mixed Fruit Juice",
        "Pineapple Juice"
    ],

    "Tea": [
        "Black Tea",
        "Green Tea",
        "Masala Tea",
        "Earl Grey Tea",
        "Chamomile Tea"
    ],

    "Coffee": [
        "Instant Coffee",
        "Ground Coffee",
        "Coffee Beans",
        "Cold Coffee"
    ],

    "Energy Drinks": [
        "Classic Energy Drink",
        "Sugar Free Energy Drink",
        "Tropical Energy Drink"
    ]
}

In [21]:
# ==========================================
# FreshMart UAE - Package Size Master
# ==========================================

package_sizes = {

    "Fresh Fruits": [
        "500g",
        "1kg",
        "2kg"
    ],

    "Fresh Vegetables": [
        "500g",
        "1kg",
        "2kg"
    ],

    "Herbs": [
        "100g",
        "250g"
    ],

    "Milk": [
        "500ml",
        "1L",
        "2L"
    ],

    "Cheese": [
        "200g",
        "500g",
        "1kg"
    ],

    "Yogurt": [
        "200g",
        "500g",
        "1kg"
    ],

    "Butter": [
        "100g",
        "250g",
        "500g"
    ],

    "Eggs": [
        "6 Pack",
        "12 Pack",
        "24 Pack"
    ],

    "Bread": [
        "400g",
        "600g",
        "800g"
    ],

    "Cakes": [
        "500g",
        "1kg",
        "2kg"
    ],

    "Pastries": [
        "100g",
        "250g"
    ],

    "Water": [
        "330ml",
        "500ml",
        "1L",
        "1.5L"
    ],

    "Soft Drinks": [
        "330ml",
        "500ml",
        "1L",
        "2L"
    ],

    "Juices": [
        "250ml",
        "500ml",
        "1L",
        "2L"
    ],

    "Tea": [
        "25 Bags",
        "50 Bags",
        "100 Bags"
    ],

    "Coffee": [
        "100g",
        "200g",
        "500g"
    ],

    "Energy Drinks": [
        "250ml",
        "330ml",
        "500ml"
    ]
}

In [22]:
# ==========================================
# FreshMart UAE - Brand Master
# ==========================================

brand_master = {

    "Fresh Fruits": ["FreshMart", "Nature Fresh", "Green Farm"],
    "Fresh Vegetables": ["FreshMart", "Nature Fresh", "Green Farm"],
    "Herbs": ["FreshMart", "Green Farm"],

    "Milk": ["Almarai", "Al Ain Farms", "Nadec", "FreshMart"],
    "Cheese": ["Almarai", "President", "Puck", "FreshMart"],
    "Yogurt": ["Almarai", "Al Ain Farms", "FreshMart"],
    "Butter": ["Lurpak", "Almarai", "FreshMart"],
    "Eggs": ["Al Ain Farms", "FreshMart"],

    "Bread": ["Modern Bakery", "L'usine", "FreshMart"],
    "Cakes": ["FreshMart", "L'usine"],
    "Pastries": ["FreshMart", "L'usine"],

    "Water": ["Masafi", "Mai Dubai", "FreshMart"],
    "Soft Drinks": ["Coca-Cola", "Pepsi", "FreshMart"],
    "Juices": ["Lacnor", "Almarai", "FreshMart"],
    "Tea": ["Lipton", "Twinings", "FreshMart"],
    "Coffee": ["Nescafe", "Davidoff", "FreshMart"],
    "Energy Drinks": ["Red Bull", "Monster", "FreshMart"]
}

In [23]:
# ==========================================
# FreshMart UAE - Product Template Master
# Part 5 : Snacks
# ==========================================

product_templates["Snacks"] = {

    "Chips": [
        "Potato Chips",
        "Tortilla Chips",
        "Kettle Chips",
        "Corn Chips",
        "Vegetable Chips"
    ],

    "Biscuits": [
        "Butter Biscuits",
        "Digestive Biscuits",
        "Cream Biscuits",
        "Chocolate Biscuits",
        "Marie Biscuits"
    ],

    "Chocolates": [
        "Milk Chocolate",
        "Dark Chocolate",
        "White Chocolate",
        "Hazelnut Chocolate",
        "Wafer Chocolate"
    ],

    "Nuts": [
        "Almonds",
        "Cashews",
        "Pistachios",
        "Mixed Nuts",
        "Peanuts"
    ]
}

In [24]:
# ==========================================
# FreshMart UAE - Product Template Master
# Part 6 : Frozen Foods
# ==========================================

product_templates["Frozen Foods"] = {

    "Frozen Vegetables": [
        "Frozen Peas",
        "Mixed Vegetables",
        "Sweet Corn",
        "Broccoli Florets",
        "Cauliflower Florets"
    ],

    "Ice Cream": [
        "Vanilla Ice Cream",
        "Chocolate Ice Cream",
        "Strawberry Ice Cream",
        "Mango Ice Cream",
        "Cookies & Cream Ice Cream"
    ],

    "Frozen Chicken": [
        "Chicken Nuggets",
        "Chicken Strips",
        "Chicken Wings",
        "Chicken Breast",
        "Chicken Burger Patty"
    ]
}

In [25]:
# ==========================================
# FreshMart UAE - Product Template Master
# Part 7 : Meat & Seafood
# ==========================================

product_templates["Meat & Seafood"] = {

    "Chicken": [
        "Whole Chicken",
        "Chicken Breast",
        "Chicken Thigh",
        "Chicken Drumsticks",
        "Chicken Mince"
    ],

    "Beef": [
        "Beef Steak",
        "Beef Mince",
        "Beef Cubes",
        "Beef Strips",
        "Ground Beef"
    ],

    "Fish": [
        "Salmon Fillet",
        "Hamour Fillet",
        "Tilapia Fillet",
        "Tuna Fillet",
        "King Fish"
    ],

    "Seafood": [
        "Shrimp",
        "Prawns",
        "Squid",
        "Crab",
        "Mussels"
    ]
}

In [26]:
# ==========================================
# FreshMart UAE - Product Template Master
# Part 8 : Pantry
# ==========================================

product_templates["Pantry"] = {

    "Rice": [
        "Basmati Rice",
        "Jasmine Rice",
        "Brown Rice",
        "Long Grain Rice",
        "Sona Masoori Rice"
    ],

    "Pasta": [
        "Spaghetti",
        "Penne",
        "Macaroni",
        "Fusilli",
        "Lasagna Sheets"
    ],

    "Flour": [
        "All Purpose Flour",
        "Whole Wheat Flour",
        "Self Raising Flour"
    ],

    "Sugar": [
        "White Sugar",
        "Brown Sugar",
        "Icing Sugar"
    ],

    "Cooking Oil": [
        "Sunflower Oil",
        "Olive Oil",
        "Canola Oil",
        "Corn Oil"
    ],

    "Spices": [
        "Black Pepper",
        "Turmeric Powder",
        "Red Chilli Powder",
        "Cumin Powder",
        "Garam Masala"
    ]
}

In [27]:
# ==========================================
# FreshMart UAE - Product Template Master
# Part 9 : Personal Care
# ==========================================

product_templates["Personal Care"] = {

    "Shampoo": [
        "Anti-Dandruff Shampoo",
        "Hair Fall Control Shampoo",
        "Moisturizing Shampoo",
        "Herbal Shampoo",
        "Daily Care Shampoo"
    ],

    "Soap": [
        "Beauty Soap",
        "Antibacterial Soap",
        "Moisturizing Soap",
        "Herbal Soap",
        "Lemon Soap"
    ],

    "Toothpaste": [
        "Whitening Toothpaste",
        "Herbal Toothpaste",
        "Sensitive Toothpaste",
        "Fresh Mint Toothpaste"
    ],

    "Skincare": [
        "Face Wash",
        "Face Cream",
        "Body Lotion",
        "Sunscreen",
        "Hand Cream"
    ]
}

In [28]:
# ==========================================
# FreshMart UAE - Product Template Master
# Part 10 : Household
# ==========================================

product_templates["Household"] = {

    "Tissue": [
        "Facial Tissue",
        "Toilet Tissue",
        "Kitchen Towels"
    ],

    "Garbage Bags": [
        "Small Garbage Bags",
        "Medium Garbage Bags",
        "Large Garbage Bags"
    ],

    "Foil": [
        "Aluminium Foil",
        "Cling Wrap",
        "Baking Paper"
    ],

    "Storage Bags": [
        "Zip Lock Bags",
        "Freezer Bags",
        "Food Storage Bags"
    ]
}

In [29]:
# ==========================================
# FreshMart UAE - Product Template Master
# Part 11 : Cleaning Supplies
# ==========================================

product_templates["Cleaning Supplies"] = {

    "Detergent": [
        "Laundry Powder",
        "Laundry Liquid",
        "Detergent Pods"
    ],

    "Floor Cleaner": [
        "Lemon Floor Cleaner",
        "Lavender Floor Cleaner",
        "Disinfectant Floor Cleaner"
    ],

    "Dishwashing Liquid": [
        "Lemon Dishwash",
        "Green Apple Dishwash",
        "Anti-Grease Dishwash"
    ]
}

In [30]:
# ==========================================
# FreshMart UAE - Product Template Master
# Part 12 : Baby Care
# ==========================================

product_templates["Baby Care"] = {

    "Diapers": [
        "Newborn Diapers",
        "Small Diapers",
        "Medium Diapers",
        "Large Diapers",
        "Extra Large Diapers"
    ],

    "Baby Food": [
        "Infant Cereal",
        "Fruit Puree",
        "Vegetable Puree",
        "Baby Formula"
    ],

    "Baby Wipes": [
        "Sensitive Baby Wipes",
        "Aloe Vera Baby Wipes",
        "Fragrance Free Baby Wipes"
    ]
}

In [31]:
print(f"Total Categories: {len(product_templates)}")

total_templates = 0

for category in product_templates.values():
    for products in category.values():
        total_templates += len(products)

print(f"Total Product Templates: {total_templates}")

Total Categories: 12
Total Product Templates: 223

In [32]:
# ==========================================
# FreshMart UAE - Product Generator
# Cell 1 : Imports & Business Rules
# ==========================================

import pandas as pd
import random
from faker import Faker
from datetime import datetime

fake = Faker()

TARGET_PRODUCTS = 900

ACTIVE_RATIO = 0.95

EXPIRY_SUBCATEGORIES = {
    "Fresh Fruits",
    "Fresh Vegetables",
    "Herbs",
    "Milk",
    "Cheese",
    "Yogurt",
    "Butter",
    "Eggs",
    "Bread",
    "Cakes",
    "Pastries",
    "Water",
    "Juices",
    "Frozen Vegetables",
    "Ice Cream",
    "Frozen Chicken",
    "Chicken",
    "Beef",
    "Fish",
    "Seafood",
    "Baby Food"
}

price_ranges = {
    "Fresh Fruits": (2, 25),
    "Fresh Vegetables": (2, 20),
    "Herbs": (1, 8),
    "Milk": (4, 18),
    "Cheese": (8, 45),
    "Yogurt": (3, 20),
    "Butter": (6, 30),
    "Eggs": (8, 35),
    "Bread": (3, 15),
    "Cakes": (20, 120),
    "Pastries": (4, 18),
    "Water": (1, 12),
    "Soft Drinks": (3, 15),
    "Juices": (5, 22),
    "Tea": (8, 40),
    "Coffee": (15, 60),
    "Energy Drinks": (8, 20),
    "Chips": (3, 18),
    "Biscuits": (4, 22),
    "Chocolates": (5, 30),
    "Nuts": (10, 60),
    "Frozen Vegetables": (8, 25),
    "Ice Cream": (12, 45),
    "Frozen Chicken": (15, 40),
    "Chicken": (12, 45),
    "Beef": (20, 80),
    "Fish": (18, 70),
    "Seafood": (25, 120),
    "Rice": (10, 60),
    "Pasta": (4, 20),
    "Flour": (5, 25),
    "Sugar": (4, 20),
    "Cooking Oil": (12, 60),
    "Spices": (3, 25),
    "Shampoo": (12, 45),
    "Soap": (3, 20),
    "Toothpaste": (6, 25),
    "Skincare": (15, 80),
    "Tissue": (4, 20),
    "Garbage Bags": (6, 18),
    "Foil": (5, 20),
    "Storage Bags": (5, 20),
    "Detergent": (15, 60),
    "Floor Cleaner": (10, 35),
    "Dishwashing Liquid": (8, 30),
    "Diapers": (35, 120),
    "Baby Food": (10, 40),
    "Baby Wipes": (8, 30)
}

In [44]:
# ==========================================
# FreshMart UAE - Product Generator
# Cell 2 : Generate Products
# ==========================================

products = []
product_names = set()
product_counter = 1

while len(products) < TARGET_PRODUCTS:

    # Random Category
    category = random.choice(list(product_templates.keys()))

    # Random Sub Category
    sub_category = random.choice(list(product_templates[category].keys()))

    # Random Template
    template = random.choice(product_templates[category][sub_category])

    # Valid Brand
    brand = random.choice(brand_master[sub_category])

    # Valid Size
    size = random.choice(package_sizes[sub_category])

    # Final Product Name
    product_name = f"{brand} {template} {size}"

    # Avoid duplicates
    if product_name in product_names:
        continue

    product_names.add(product_name)

    # Product ID
    product_id = f"P{product_counter:04d}"

    # Unit Cost (60-80% of Selling Price)
    min_price, max_price = price_ranges[sub_category]

    selling_price = round(random.uniform(min_price, max_price), 2)

    cost_percentage = random.uniform(0.60, 0.80)

    unit_cost = round(selling_price * cost_percentage, 2)

    profit_margin = round(
        ((selling_price - unit_cost) / selling_price) * 100,
        2
    )

    # Barcode
    barcode = fake.unique.ean13()

    # Expiry
    expiry_required = (
        "Yes"
        if sub_category in EXPIRY_SUBCATEGORIES
        else "No"
    )

    # Launch Date
    launch_date = fake.date_between(
        start_date="-5y",
        end_date="today"
    )

    # Status
    status = random.choices(
        ["Active", "Discontinued"],
        weights=[95, 5]
    )[0]

    products.append({
        "product_id": product_id,
        "product_name": product_name,
        "category": category,
        "sub_category": sub_category,
        "brand": brand,
        "size": size,
        "unit_cost": unit_cost,
        "selling_price": selling_price,
        "profit_margin": profit_margin,
        "barcode": barcode,
        "expiry_required": expiry_required,
        "launch_date": launch_date,
        "status": status
    })

    product_counter += 1

products_df = pd.DataFrame(products)
products_df.to_csv(
    "products.csv",
    index=False
)

print("products.csv created successfully")
print("Total Products:", len(products_df))

products.csv created successfully
Total Products: 900

In [34]:
brand_master.update({

    "Chips": ["Pringles", "Lays", "FreshMart"],
    "Biscuits": ["Oreo", "McVitie's", "FreshMart"],
    "Chocolates": ["KitKat", "Galaxy", "FreshMart"],
    "Nuts": ["Bayara", "FreshMart"],

    "Frozen Vegetables": ["FreshMart", "Americana"],
    "Ice Cream": ["Igloo", "London Dairy", "FreshMart"],
    "Frozen Chicken": ["Americana", "Al Islami", "FreshMart"],

    "Chicken": ["Al Islami", "Sadia", "FreshMart"],
    "Beef": ["FreshMart", "Mazza"],
    "Fish": ["FreshMart", "Ocean Fresh"],
    "Seafood": ["FreshMart", "Ocean Fresh"],

    "Rice": ["India Gate", "Daawat", "FreshMart"],
    "Pasta": ["Barilla", "FreshMart"],
    "Flour": ["Al Baker", "FreshMart"],
    "Sugar": ["Al Khaleej", "FreshMart"],
    "Cooking Oil": ["Noor", "FreshMart"],
    "Spices": ["Shan", "FreshMart"],

    "Shampoo": ["Pantene", "Head & Shoulders", "FreshMart"],
    "Soap": ["Dove", "Lux", "FreshMart"],
    "Toothpaste": ["Colgate", "Sensodyne", "FreshMart"],
    "Skincare": ["Nivea", "Vaseline", "FreshMart"],

    "Tissue": ["Fine", "FreshMart"],
    "Garbage Bags": ["FreshMart"],
    "Foil": ["FreshMart"],
    "Storage Bags": ["FreshMart"],

    "Detergent": ["Persil", "Ariel", "FreshMart"],
    "Floor Cleaner": ["Dettol", "FreshMart"],
    "Dishwashing Liquid": ["Fairy", "FreshMart"],

    "Diapers": ["Pampers", "FreshMart"],
    "Baby Food": ["Cerelac", "FreshMart"],
    "Baby Wipes": ["Johnson's", "FreshMart"]

})

In [36]:
# Check missing brand mappings

missing_brands = []

for category in product_templates:
    for sub_category in product_templates[category]:
        if sub_category not in brand_master:
            missing_brands.append(sub_category)

print(missing_brands)

[]

In [39]:
# Check missing package size mappings

missing_sizes = []

for category in product_templates:
    for sub_category in product_templates[category]:
        if sub_category not in package_sizes:
            missing_sizes.append(sub_category)

print(missing_sizes)

[]

In [38]:
# ==========================================
# FreshMart UAE - Package Size Updates
# ==========================================

package_sizes.update({

    "Chips": ["50g", "100g", "200g"],
    "Biscuits": ["100g", "250g", "500g"],
    "Chocolates": ["50g", "100g", "200g"],
    "Nuts": ["100g", "250g", "500g"],

    "Frozen Vegetables": ["500g", "1kg"],
    "Ice Cream": ["500ml", "1L"],
    "Frozen Chicken": ["500g", "1kg"],

    "Chicken": ["500g", "1kg", "2kg"],
    "Beef": ["500g", "1kg"],
    "Fish": ["500g", "1kg"],
    "Seafood": ["500g", "1kg"],

    "Rice": ["1kg", "5kg", "10kg"],
    "Pasta": ["250g", "500g", "1kg"],
    "Flour": ["1kg", "5kg"],
    "Sugar": ["1kg", "5kg"],
    "Cooking Oil": ["500ml", "1L", "2L", "5L"],
    "Spices": ["50g", "100g", "250g"],

    "Shampoo": ["200ml", "400ml", "700ml"],
    "Soap": ["75g", "125g", "150g"],
    "Toothpaste": ["50ml", "100ml", "150ml"],
    "Skincare": ["50ml", "100ml", "200ml"],

    "Tissue": ["1 Pack", "4 Pack", "12 Pack"],
    "Garbage Bags": ["20 Bags", "50 Bags", "100 Bags"],
    "Foil": ["10m", "20m", "50m"],
    "Storage Bags": ["20 Bags", "50 Bags"],

    "Detergent": ["500g", "1kg", "3kg"],
    "Floor Cleaner": ["500ml", "1L", "2L"],
    "Dishwashing Liquid": ["500ml", "1L"],

    "Diapers": ["Small Pack", "Medium Pack", "Large Pack"],
    "Baby Food": ["200g", "400g", "800g"],
    "Baby Wipes": ["40 Sheets", "80 Sheets"]
})

In [41]:
# ==========================================
# FreshMart UAE - Product Data Validation
# ==========================================

import pandas as pd

products = pd.read_csv("products.csv")

print("Total Products:", len(products))

print("\nMissing Values:")
print(products.isnull().sum())

print("\nDuplicate Products:")
print(products.duplicated().sum())

print("\nSample Products:")
products.head()

FileNotFoundError: [Errno 2] No such file or directory: 'products.csv'

In [45]:
import os

# Check files available in current directory

files = os.listdir()

files

['.ipynb_checkpoints',
 'customers.csv',
 'FreshMart_Dataset_Generator.ipynb',
 'products.csv']

In [46]:
# ==========================================
# FreshMart UAE - Product Validation
# ==========================================

import pandas as pd

products = pd.read_csv("products.csv")

print("Total Products:", len(products))

print("\nMissing Values:")
print(products.isnull().sum())

print("\nDuplicate Product Names:")
print(products["product_name"].duplicated().sum())

print("\nCategory Count:")
print(products["category"].value_counts())

print("\nTop Brands:")
print(products["brand"].value_counts().head(10))

print("\nPrice Summary:")
print(products["selling_price"].describe())

print("\nSample Products:")
products.head()

Total Products: 900

Missing Values:
product_id         0
product_name       0
category           0
sub_category       0
brand              0
size               0
unit_cost          0
selling_price      0
profit_margin      0
barcode            0
expiry_required    0
launch_date        0
status             0
dtype: int64

Duplicate Product Names:
0

Category Count:
category
Personal Care          97
Snacks                 92
Pantry                 92
Beverages              92
Dairy & Eggs           91
Fruits & Vegetables    86
Meat & Seafood         72
Bakery                 70
Frozen Foods           59
Baby Care              56
Cleaning Supplies      52
Household              41
Name: count, dtype: int64

Top Brands:
brand
FreshMart       380
Green Farm       36
Almarai          29
L'usine          28
Nature Fresh     19
Al Islami        19
Al Ain Farms     15
Ocean Fresh      15
Pampers          13
Vaseline         12
Name: count, dtype: int64

Price Summary:
count    900.000000
mean      23.554867
std       19.859775
min        1.160000
25%       10.787500
50%       17.335000
75%       30.385000
max      119.820000
Name: selling_price, dtype: float64

Sample Products:

,product_id,product_name,category,sub_category,brand,size,unit_cost,selling_price,profit_margin,barcode,expiry_required,launch_date,status
0,P0001,FreshMart Lemon Dishwash 500ml,Cleaning Supplies,Dishwashing Liquid,FreshMart,500ml,20.94,27.62,24.19,2750732794002,No,2024-08-11,Active
1,P0002,McVitie's Chocolate Biscuits 250g,Snacks,Biscuits,McVitie's,250g,7.73,9.97,22.47,4157447233099,No,2025-06-06,Active
2,P0003,Cerelac Baby Formula 400g,Baby Care,Baby Food,Cerelac,400g,24.86,36.04,31.02,330867318711,Yes,2022-02-13,Active
3,P0004,FreshMart Digestive Biscuits 250g,Snacks,Biscuits,FreshMart,250g,7.45,11.20,33.48,5671848434200,No,2024-05-31,Active
4,P0005,FreshMart Disinfectant Floor Cleaner 1L,Cleaning Supplies,Floor Cleaner,FreshMart,1L,22.38,32.72,31.60,8934060730190,No,2025-05-11,Active

In [47]:
import pandas as pd

customers = pd.read_csv("customers.csv")

print(customers.columns)
print(customers.head())

Index(['customer_id', 'customer_name', 'gender', 'age', 'city', 'emirate',
       'segment', 'loyalty_status', 'email', 'phone', 'join_date'],
      dtype='str')
  customer_id    customer_name  gender  age           city        emirate  \
0      C00001     Jessica Long  Female   35       Fujairah       Fujairah
1      C00002  Stephanie Smith    Male   42       Fujairah       Fujairah
2      C00003     Michael Mora    Male   69        Sharjah        Sharjah
3      C00004      Kevin Bryan  Female   39          Dubai          Dubai
4      C00005     Mathew Foley  Female   65  Umm Al Quwain  Umm Al Quwain

       segment loyalty_status                   email             phone  \
0  Home Office         Silver  jesseclark@example.net  001-242-462-4150
1     Consumer           Gold     terri67@example.net      984.981.9065
2     Consumer         Silver    vsanders@example.com  537.731.6463x890
3     Consumer         Silver   ryanstone@example.org      865.241.4551
4     Consumer         Silver       cwood@example.com  288-223-6762x170

    join_date
0  2024-11-30
1  2024-04-19
2  2023-12-13
3  2025-06-25
4  2022-08-30

In [48]:
import pandas as pd
import random
from faker import Faker
from datetime import timedelta

fake = Faker()

customers = pd.read_csv("customers.csv")
products = pd.read_csv("products.csv")

In [49]:
# ==========================================
# FreshMart UAE - Supplier Configuration
# ==========================================

supplier_categories = {

    "Dairy Supplier": [
        "Dairy & Eggs"
    ],

    "Meat Supplier": [
        "Meat & Seafood",
        "Frozen Foods"
    ],

    "Fresh Produce Supplier": [
        "Fruits & Vegetables"
    ],

    "Bakery Supplier": [
        "Bakery"
    ],

    "Food Manufacturer": [
        "Snacks",
        "Pantry",
        "Beverages"
    ],

    "Personal Care Manufacturer": [
        "Personal Care"
    ],

    "Baby Care Manufacturer": [
        "Baby Care"
    ],

    "Cleaning Supplier": [
        "Cleaning Supplies",
        "Household"
    ]
}

In [50]:
# ==========================================
# FreshMart UAE - Supplier Name Master
# ==========================================

supplier_master = {

    "Dairy & Eggs": [
        "Al Ain Farms",
        "Almarai UAE",
        "National Dairy Company",
        "Fresh Dairy Trading LLC"
    ],

    "Meat & Seafood": [
        "Al Islami Foods",
        "JBS Foods UAE",
        "Gulf Meat Suppliers",
        "Ocean Fresh Trading"
    ],

    "Frozen Foods": [
        "Frozen Food Trading LLC",
        "Al Kabeer UAE",
        "Polar Foods"
    ],

    "Fruits & Vegetables": [
        "Fresh Produce Trading LLC",
        "Green Valley Suppliers",
        "Dubai Fresh Foods"
    ],

    "Bakery": [
        "Modern Bakery LLC",
        "L'usine Supplier",
        "Golden Bakery Trading"
    ],

    "Snacks": [
        "PepsiCo UAE",
        "Mondelez UAE",
        "Snack Distribution LLC"
    ],

    "Pantry": [
        "National Food Products",
        "Foodco Trading",
        "Gulf Pantry Suppliers"
    ],

    "Beverages": [
        "Nestle UAE",
        "Coca Cola UAE",
        "Pepsi Distribution UAE"
    ],

    "Personal Care": [
        "Unilever UAE",
        "Procter & Gamble UAE",
        "Beauty Care Trading"
    ],

    "Baby Care": [
        "Johnson & Johnson UAE",
        "Nestle Baby Care",
        "Baby Products Trading"
    ],

    "Cleaning Supplies": [
        "Henkel UAE",
        "Clean Solutions LLC",
        "Home Care Trading"
    ],

    "Household": [
        "Home Essentials Trading",
        "Household Supplies LLC",
        "Dubai General Trading"
    ]
}

In [51]:
supplier_master["Dairy & Eggs"]

['Al Ain Farms',
 'Almarai UAE',
 'National Dairy Company',
 'Fresh Dairy Trading LLC']

In [53]:
# ==========================================
# FreshMart UAE - Supplier Generator
# ==========================================

NUM_SUPPLIERS = 100

import pandas as pd
import random
from faker import Faker

fake = Faker()

suppliers = []

supplier_counter = 1


# UAE Locations

supplier_locations = {
    "Dubai": "Dubai",
    "Abu Dhabi": "Abu Dhabi",
    "Sharjah": "Sharjah",
    "Ajman": "Ajman",
    "Ras Al Khaimah": "Ras Al Khaimah",
    "Fujairah": "Fujairah",
    "Umm Al Quwain": "Umm Al Quwain",
    "Al Ain": "Abu Dhabi"
}


# Supplier naming variations

supplier_suffixes = [
    "Distribution Division",
    "Wholesale Partner",
    "Trading LLC",
    "UAE Branch",
    "Retail Supply Division",
    "Food Trading",
    "Commercial Division",
    "Regional Supplier"
]


existing_names = set()


while len(suppliers) < NUM_SUPPLIERS:

    # Select category type
    supplier_type_key = random.choice(
        list(supplier_categories.keys())
    )

    # Select actual category
    category = random.choice(
        supplier_categories[supplier_type_key]
    )

    # Select base supplier name
    base_name = random.choice(
        supplier_master[category]
    )


    # Create unique supplier name

    supplier_name = (
        base_name
        + " - "
        + random.choice(supplier_suffixes)
    )


    # Avoid duplicates

    if supplier_name in existing_names:
        continue


    existing_names.add(supplier_name)


    city = random.choice(
        list(supplier_locations.keys())
    )


    supplier_id = f"S{supplier_counter:04d}"


    suppliers.append({

        "supplier_id": supplier_id,

        "supplier_name": supplier_name,

        "supplier_type": random.choice(
            [
                "Local",
                "International"
            ]
        ),

        "category": category,

        "city": city,

        "emirate": supplier_locations[city],

        "contact_person": fake.name(),

        "email": fake.company_email(),

        "phone": fake.phone_number(),

        "contract_start_date": fake.date_between(
            start_date="-10y",
            end_date="-1y"
        ),

        "payment_terms": random.choice(
            [
                "30 Days",
                "45 Days",
                "60 Days"
            ]
        ),

        "status": random.choice(
            [
                "Active",
                "Inactive"
            ]
        )
    })


    supplier_counter += 1



suppliers_df = pd.DataFrame(suppliers)


suppliers_df.to_csv(
    "suppliers.csv",
    index=False
)


print("suppliers.csv created successfully")
print("Total Suppliers:", len(suppliers_df))

suppliers.csv created successfully
Total Suppliers: 100

In [54]:
# ==========================================
# FreshMart UAE - Supplier Validation
# ==========================================

import pandas as pd

suppliers = pd.read_csv("suppliers.csv")


print("Total Suppliers:", len(suppliers))


print("\nMissing Values:")
print(suppliers.isnull().sum())


print("\nDuplicate Supplier Names:")
print(
    suppliers["supplier_name"].duplicated().sum()
)


print("\nCategory Distribution:")
print(
    suppliers["category"].value_counts()
)


print("\nSupplier Type Distribution:")
print(
    suppliers["supplier_type"].value_counts()
)


print("\nSample Suppliers:")
suppliers.head()

Total Suppliers: 100

Missing Values:
supplier_id            0
supplier_name          0
supplier_type          0
category               0
city                   0
emirate                0
contact_person         0
email                  0
phone                  0
contract_start_date    0
payment_terms          0
status                 0
dtype: int64

Duplicate Supplier Names:
0

Category Distribution:
category
Dairy & Eggs           14
Fruits & Vegetables    14
Personal Care          12
Bakery                 11
Meat & Seafood         10
Baby Care              10
Frozen Foods            8
Cleaning Supplies       8
Pantry                  7
Household               4
Snacks                  1
Beverages               1
Name: count, dtype: int64

Supplier Type Distribution:
supplier_type
International    56
Local            44
Name: count, dtype: int64

Sample Suppliers:

,supplier_id,supplier_name,supplier_type,category,city,emirate,contact_person,email,phone,contract_start_date,payment_terms,status
0,S0001,Fresh Dairy Trading LLC - Trading LLC,International,Dairy & Eggs,Al Ain,Abu Dhabi,Ralph Hale,qcarroll@thomas.com,6738074519,2016-08-26,45 Days,Inactive
1,S0002,Dubai Fresh Foods - Retail Supply Division,International,Fruits & Vegetables,Abu Dhabi,Abu Dhabi,Ryan Robertson,stewartstephanie@thomas.net,405-717-7864x668,2025-03-06,30 Days,Inactive
2,S0003,Gulf Meat Suppliers - Trading LLC,International,Meat & Seafood,Fujairah,Fujairah,Leah Robbins,aprildaniel@mcclure.com,001-994-926-3445,2023-09-18,45 Days,Active
3,S0004,Modern Bakery LLC - Commercial Division,Local,Bakery,Dubai,Dubai,Richard Nelson,vanessa23@simmons.com,+1-259-365-5561x23826,2018-08-30,30 Days,Inactive
4,S0005,Golden Bakery Trading - Wholesale Partner,International,Bakery,Fujairah,Fujairah,Kelsey Turner,shelia79@bowen.com,001-855-342-9387x764,2021-01-05,60 Days,Active

In [55]:
# ==========================================
# FreshMart UAE - Store Generator
# ==========================================

import pandas as pd
import random
from faker import Faker

fake = Faker()

NUM_STORES = 30

store_distribution = {
    "Dubai": 10,
    "Abu Dhabi": 6,
    "Sharjah": 5,
    "Ajman": 2,
    "Ras Al Khaimah": 2,
    "Fujairah": 2,
    "Umm Al Quwain": 1,
    "Al Ain": 2
}

emirate_mapping = {
    "Dubai": "Dubai",
    "Abu Dhabi": "Abu Dhabi",
    "Sharjah": "Sharjah",
    "Ajman": "Ajman",
    "Ras Al Khaimah": "Ras Al Khaimah",
    "Fujairah": "Fujairah",
    "Umm Al Quwain": "Umm Al Quwain",
    "Al Ain": "Abu Dhabi"
}

store_types = (
    ["Hypermarket"] * 6 +
    ["Supermarket"] * 15 +
    ["Express"] * 9
)

stores = []
store_counter = 1

for city, total in store_distribution.items():

    for i in range(total):

        store_id = f"ST{store_counter:03d}"

        store_name = f"FreshMart {city} {i+1}"

        store_type = random.choice(store_types)

        if store_type == "Hypermarket":
            size = random.randint(3500,6000)
            capacity = random.randint(2500,4000)

        elif store_type == "Supermarket":
            size = random.randint(1500,3500)
            capacity = random.randint(1200,2500)

        else:
            size = random.randint(500,1500)
            capacity = random.randint(300,1000)

        stores.append({

            "store_id": store_id,

            "store_name": store_name,

            "store_type": store_type,

            "city": city,

            "emirate": emirate_mapping[city],

            "store_size_sqft": size,

            "daily_customer_capacity": capacity,

            "opening_date": fake.date_between(
                start_date="-15y",
                end_date="-6m"
            ),

            "store_manager": fake.name(),

            "status": random.choices(
                ["Active","Renovation"],
                weights=[95,5]
            )[0]

        })

        store_counter += 1

stores_df = pd.DataFrame(stores)

stores_df.to_csv("stores.csv", index=False)

print("stores.csv created successfully")
print("Total Stores:", len(stores_df))

stores_df.head()

stores.csv created successfully
Total Stores: 30

,store_id,store_name,store_type,city,emirate,store_size_sqft,daily_customer_capacity,opening_date,store_manager,status
0,ST001,FreshMart Dubai 1,Supermarket,Dubai,Dubai,1627,2206,2020-04-29,Jessica Baldwin,Active
1,ST002,FreshMart Dubai 2,Supermarket,Dubai,Dubai,1888,1206,2015-12-13,Becky Mcbride,Renovation
2,ST003,FreshMart Dubai 3,Hypermarket,Dubai,Dubai,4246,3923,2014-09-11,Janet Park,Active
3,ST004,FreshMart Dubai 4,Supermarket,Dubai,Dubai,3110,1450,2021-01-07,Leslie Holmes,Active
4,ST005,FreshMart Dubai 5,Express,Dubai,Dubai,611,408,2022-10-18,Joseph Mccormick,Active

In [56]:
stores = pd.read_csv("stores.csv")

print("Total Stores:", len(stores))
print("\nMissing Values:")
print(stores.isnull().sum())

print("\nDuplicate Store IDs:")
print(stores["store_id"].duplicated().sum())

print("\nStore Type Distribution:")
print(stores["store_type"].value_counts())

print("\nCity Distribution:")
print(stores["city"].value_counts())

stores.head()

Total Stores: 30

Missing Values:
store_id                   0
store_name                 0
store_type                 0
city                       0
emirate                    0
store_size_sqft            0
daily_customer_capacity    0
opening_date               0
store_manager              0
status                     0
dtype: int64

Duplicate Store IDs:
0

Store Type Distribution:
store_type
Supermarket    16
Express         9
Hypermarket     5
Name: count, dtype: int64

City Distribution:
city
Dubai             10
Abu Dhabi          6
Sharjah            5
Ajman              2
Ras Al Khaimah     2
Fujairah           2
Al Ain             2
Umm Al Quwain      1
Name: count, dtype: int64

,store_id,store_name,store_type,city,emirate,store_size_sqft,daily_customer_capacity,opening_date,store_manager,status
0,ST001,FreshMart Dubai 1,Supermarket,Dubai,Dubai,1627,2206,2020-04-29,Jessica Baldwin,Active
1,ST002,FreshMart Dubai 2,Supermarket,Dubai,Dubai,1888,1206,2015-12-13,Becky Mcbride,Renovation
2,ST003,FreshMart Dubai 3,Hypermarket,Dubai,Dubai,4246,3923,2014-09-11,Janet Park,Active
3,ST004,FreshMart Dubai 4,Supermarket,Dubai,Dubai,3110,1450,2021-01-07,Leslie Holmes,Active
4,ST005,FreshMart Dubai 5,Express,Dubai,Dubai,611,408,2022-10-18,Joseph Mccormick,Active

In [57]:
# ==========================================
# FreshMart UAE - Employee Generator
# ==========================================

import pandas as pd
import random
from faker import Faker

fake = Faker()

NUM_EMPLOYEES = 150

stores = pd.read_csv("stores.csv")

job_roles = {
    "Store Manager": 10,
    "Assistant Manager": 15,
    "Supervisor": 25,
    "Cashier": 55,
    "Inventory Associate": 25,
    "Customer Service Executive": 20
}

employees = []

employee_counter = 1

# Create role pool
role_pool = []

for role, count in job_roles.items():
    role_pool.extend([role] * count)

random.shuffle(role_pool)

for role in role_pool:

    store = stores.sample(1).iloc[0]

    hire_date = fake.date_between(
        start_date="-8y",
        end_date="-30d"
    )

    salary_ranges = {
        "Store Manager": (12000,18000),
        "Assistant Manager": (8000,12000),
        "Supervisor": (5000,8000),
        "Cashier": (2500,4500),
        "Inventory Associate": (3000,5000),
        "Customer Service Executive": (3000,5000)
    }

    salary = random.randint(
        salary_ranges[role][0],
        salary_ranges[role][1]
    )

    employees.append({

        "employee_id": f"E{employee_counter:04d}",

        "employee_name": fake.name(),

        "gender": random.choice(
            ["Male","Female"]
        ),

        "age": random.randint(21,60),

        "job_role": role,

        "store_id": store["store_id"],

        "store_name": store["store_name"],

        "hire_date": hire_date,

        "salary": salary,

        "status": random.choices(
            ["Active","On Leave","Resigned"],
            weights=[90,5,5]
        )[0]

    })

    employee_counter += 1

employees_df = pd.DataFrame(employees)

employees_df.to_csv(
    "employees.csv",
    index=False
)

print("employees.csv created successfully")
print("Total Employees:", len(employees_df))

employees_df.head()

employees.csv created successfully
Total Employees: 150

,employee_id,employee_name,gender,age,job_role,store_id,store_name,hire_date,salary,status
0,E0001,Brandon Taylor,Female,28,Assistant Manager,ST022,FreshMart Ajman 1,2024-12-26,11406,Active
1,E0002,Jeffrey Morgan,Male,23,Store Manager,ST009,FreshMart Dubai 9,2022-02-23,14462,Active
2,E0003,Shannon Vargas,Female,23,Cashier,ST016,FreshMart Abu Dhabi 6,2023-11-15,3528,Active
3,E0004,Steven Lamb DDS,Male,27,Supervisor,ST004,FreshMart Dubai 4,2026-03-03,5077,Active
4,E0005,Brooke Shaw,Male,22,Customer Service Executive,ST004,FreshMart Dubai 4,2019-08-13,4598,Active

In [58]:
employees = pd.read_csv("employees.csv")

print("Total Employees:", len(employees))

print("\nMissing Values:")
print(employees.isnull().sum())

print("\nDuplicate Employee IDs:")
print(employees["employee_id"].duplicated().sum())

print("\nJob Role Distribution:")
print(employees["job_role"].value_counts())

print("\nEmployee Status:")
print(employees["status"].value_counts())

employees.head()

Total Employees: 150

Missing Values:
employee_id      0
employee_name    0
gender           0
age              0
job_role         0
store_id         0
store_name       0
hire_date        0
salary           0
status           0
dtype: int64

Duplicate Employee IDs:
0

Job Role Distribution:
job_role
Cashier                       55
Supervisor                    25
Inventory Associate           25
Customer Service Executive    20
Assistant Manager             15
Store Manager                 10
Name: count, dtype: int64

Employee Status:
status
Active      137
Resigned      7
On Leave      6
Name: count, dtype: int64

,employee_id,employee_name,gender,age,job_role,store_id,store_name,hire_date,salary,status
0,E0001,Brandon Taylor,Female,28,Assistant Manager,ST022,FreshMart Ajman 1,2024-12-26,11406,Active
1,E0002,Jeffrey Morgan,Male,23,Store Manager,ST009,FreshMart Dubai 9,2022-02-23,14462,Active
2,E0003,Shannon Vargas,Female,23,Cashier,ST016,FreshMart Abu Dhabi 6,2023-11-15,3528,Active
3,E0004,Steven Lamb DDS,Male,27,Supervisor,ST004,FreshMart Dubai 4,2026-03-03,5077,Active
4,E0005,Brooke Shaw,Male,22,Customer Service Executive,ST004,FreshMart Dubai 4,2019-08-13,4598,Active

In [59]:
# ==========================================
# FreshMart UAE - Order Configuration
# ==========================================

NUM_ORDERS = 40000

ORDER_STATUS = {
    "Delivered": 85,
    "Cancelled": 5,
    "Returned": 6,
    "Processing": 3,
    "Shipped": 1
}

PAYMENT_METHODS = {
    "Card": 45,
    "Cash on Delivery": 20,
    "Apple Pay": 15,
    "Google Pay": 10,
    "Wallet": 10
}

DELIVERY_TYPE = {
    "Standard": 70,
    "Express": 20,
    "Pickup": 10
}

In [60]:
# ==========================================
# FreshMart UAE - Order Generator
# ==========================================

import pandas as pd
import random
from faker import Faker
from datetime import timedelta

fake = Faker()

customers = pd.read_csv("customers.csv")
stores = pd.read_csv("stores.csv")

orders = []

status_list = list(ORDER_STATUS.keys())
status_weights = list(ORDER_STATUS.values())

payment_list = list(PAYMENT_METHODS.keys())
payment_weights = list(PAYMENT_METHODS.values())

delivery_list = list(DELIVERY_TYPE.keys())
delivery_weights = list(DELIVERY_TYPE.values())

for order_num in range(1, NUM_ORDERS + 1):

    customer = customers.sample(1).iloc[0]
    store = stores.sample(1).iloc[0]

    order_date = fake.date_time_between(
        start_date="-2y",
        end_date="now"
    )

    order_status = random.choices(
        status_list,
        weights=status_weights,
        k=1
    )[0]

    delivery_type = random.choices(
        delivery_list,
        weights=delivery_weights,
        k=1
    )[0]

    payment_method = random.choices(
        payment_list,
        weights=payment_weights,
        k=1
    )[0]

    # Delivery Days

    if order_status == "Cancelled":
        delivery_date = None

    elif order_status == "Processing":
        delivery_date = None

    else:

        if delivery_type == "Express":
            days = random.randint(0, 1)

        elif delivery_type == "Standard":
            days = random.randint(2, 5)

        else:
            days = random.randint(0, 2)

        delivery_date = (
            order_date + timedelta(days=days)
        ).date()

    shipping_fee = {
        "Standard": 10,
        "Express": 25,
        "Pickup": 0
    }[delivery_type]

    orders.append({

        "order_id": f"O{order_num:06d}",

        "customer_id": customer["customer_id"],

        "store_id": store["store_id"],

        "order_date": order_date.date(),

        "delivery_date": delivery_date,

        "order_status": order_status,

        "delivery_type": delivery_type,

        "payment_method": payment_method,

        "shipping_fee": shipping_fee

    })

orders_df = pd.DataFrame(orders)

orders_df.to_csv(
    "orders.csv",
    index=False
)

print("orders.csv created successfully")
print("Total Orders:", len(orders_df))

orders_df.head()

orders.csv created successfully
Total Orders: 40000

,order_id,customer_id,store_id,order_date,delivery_date,order_status,delivery_type,payment_method,shipping_fee
0,O000001,C05649,ST027,2024-09-20,2024-09-21,Returned,Pickup,Card,0
1,O000002,C04613,ST023,2026-02-07,2026-02-09,Delivered,Standard,Apple Pay,10
2,O000003,C06669,ST016,2024-08-30,2024-08-31,Delivered,Pickup,Card,0
3,O000004,C07999,ST028,2025-03-08,None,Processing,Express,Card,25
4,O000005,C09452,ST012,2026-01-18,2026-01-22,Delivered,Standard,Cash on Delivery,10

In [61]:
orders = pd.read_csv("orders.csv")

print("Total Orders:", len(orders))

print("\nMissing Values:")
print(orders.isnull().sum())

print("\nDuplicate Order IDs:")
print(orders["order_id"].duplicated().sum())

print("\nOrder Status:")
print(orders["order_status"].value_counts())

print("\nPayment Methods:")
print(orders["payment_method"].value_counts())

print("\nDelivery Type:")
print(orders["delivery_type"].value_counts())

orders.head()

Total Orders: 40000

Missing Values:
order_id             0
customer_id          0
store_id             0
order_date           0
delivery_date     3194
order_status         0
delivery_type        0
payment_method       0
shipping_fee         0
dtype: int64

Duplicate Order IDs:
0

Order Status:
order_status
Delivered     34028
Returned       2382
Cancelled      1971
Processing     1223
Shipped         396
Name: count, dtype: int64

Payment Methods:
payment_method
Card                17994
Cash on Delivery     8194
Apple Pay            5931
Wallet               3968
Google Pay           3913
Name: count, dtype: int64

Delivery Type:
delivery_type
Standard    28075
Express      7966
Pickup       3959
Name: count, dtype: int64

,order_id,customer_id,store_id,order_date,delivery_date,order_status,delivery_type,payment_method,shipping_fee
0,O000001,C05649,ST027,2024-09-20,2024-09-21,Returned,Pickup,Card,0
1,O000002,C04613,ST023,2026-02-07,2026-02-09,Delivered,Standard,Apple Pay,10
2,O000003,C06669,ST016,2024-08-30,2024-08-31,Delivered,Pickup,Card,0
3,O000004,C07999,ST028,2025-03-08,NaN,Processing,Express,Card,25
4,O000005,C09452,ST012,2026-01-18,2026-01-22,Delivered,Standard,Cash on Delivery,10

In [62]:
# ==========================================
# FreshMart UAE - Order Items Configuration
# ==========================================

MIN_ITEMS_PER_ORDER = 1
MAX_ITEMS_PER_ORDER = 5

QUANTITY_WEIGHTS = {
    1: 55,
    2: 25,
    3: 12,
    4: 5,
    5: 3
}

DISCOUNT_OPTIONS = {
    0: 40,
    5: 25,
    10: 20,
    15: 10,
    20: 5
}

In [63]:
# ==========================================
# FreshMart UAE - Order Items Generator
# ==========================================

import pandas as pd
import random

orders = pd.read_csv("orders.csv")
products = pd.read_csv("products.csv")

order_items = []

item_counter = 1

quantity_values = list(QUANTITY_WEIGHTS.keys())
quantity_weights = list(QUANTITY_WEIGHTS.values())

discount_values = list(DISCOUNT_OPTIONS.keys())
discount_weights = list(DISCOUNT_OPTIONS.values())

for _, order in orders.iterrows():

    items_in_order = random.randint(
        MIN_ITEMS_PER_ORDER,
        MAX_ITEMS_PER_ORDER
    )

    selected_products = products.sample(
        n=items_in_order,
        replace=False
    )

    for _, product in selected_products.iterrows():

        quantity = random.choices(
            quantity_values,
            weights=quantity_weights,
            k=1
        )[0]

        unit_price = float(product["selling_price"])

        discount_percent = random.choices(
            discount_values,
            weights=discount_weights,
            k=1
        )[0]

        discount_amount = round(
            unit_price * discount_percent / 100,
            2
        )

        final_unit_price = round(
            unit_price - discount_amount,
            2
        )

        line_total = round(
            final_unit_price * quantity,
            2
        )

        order_items.append({

            "order_item_id": f"OI{item_counter:07d}",

            "order_id": order["order_id"],

            "product_id": product["product_id"],

            "quantity": quantity,

            "unit_price": unit_price,

            "discount_percent": discount_percent,

            "discount_amount": discount_amount,

            "final_unit_price": final_unit_price,

            "line_total": line_total

        })

        item_counter += 1

order_items_df = pd.DataFrame(order_items)

order_items_df.to_csv(
    "order_items.csv",
    index=False
)

print("order_items.csv created successfully")
print("Total Order Items:", len(order_items_df))

order_items_df.head()

order_items.csv created successfully
Total Order Items: 119726

,order_item_id,order_id,product_id,quantity,unit_price,discount_percent,discount_amount,final_unit_price,line_total
0,OI0000001,O000001,P0628,1,5.15,0,0.00,5.15,5.15
1,OI0000002,O000001,P0852,1,20.56,0,0.00,20.56,20.56
2,OI0000003,O000001,P0603,3,15.07,0,0.00,15.07,45.21
3,OI0000004,O000001,P0790,1,4.40,20,0.88,3.52,3.52
4,OI0000005,O000002,P0046,1,6.66,10,0.67,5.99,5.99

In [64]:
# ==========================================
# FreshMart UAE - Order Items Validation
# ==========================================

import pandas as pd

order_items = pd.read_csv("order_items.csv")

print("Total Order Items:", len(order_items))

print("\nMissing Values:")
print(order_items.isnull().sum())

print("\nDuplicate Order Item IDs:")
print(order_items["order_item_id"].duplicated().sum())

print("\nAverage Items Per Order:")
print(round(
    order_items.groupby("order_id").size().mean(),
    2
))

print("\nQuantity Distribution:")
print(order_items["quantity"].value_counts().sort_index())

print("\nDiscount Distribution:")
print(order_items["discount_percent"].value_counts().sort_index())

print("\nRevenue Summary:")
print(order_items["line_total"].describe())

print("\nSample Data:")
display(order_items.head())

Total Order Items: 119726

Missing Values:
order_item_id       0
order_id            0
product_id          0
quantity            0
unit_price          0
discount_percent    0
discount_amount     0
final_unit_price    0
line_total          0
dtype: int64

Duplicate Order Item IDs:
0

Average Items Per Order:
2.99

Quantity Distribution:
quantity
1    65842
2    29928
3    14389
4     6009
5     3558
Name: count, dtype: int64

Discount Distribution:
discount_percent
0     47729
5     29953
10    24086
15    12093
20     5865
Name: count, dtype: int64

Revenue Summary:
count    119726.000000
mean         39.120168
std          44.709092
min           0.930000
25%          13.270000
50%          24.840000
75%          47.370000
max         599.100000
Name: line_total, dtype: float64

Sample Data:

,order_item_id,order_id,product_id,quantity,unit_price,discount_percent,discount_amount,final_unit_price,line_total
0,OI0000001,O000001,P0628,1,5.15,0,0.00,5.15,5.15
1,OI0000002,O000001,P0852,1,20.56,0,0.00,20.56,20.56
2,OI0000003,O000001,P0603,3,15.07,0,0.00,15.07,45.21
3,OI0000004,O000001,P0790,1,4.40,20,0.88,3.52,3.52
4,OI0000005,O000002,P0046,1,6.66,10,0.67,5.99,5.99

In [65]:
# ==========================================
# FreshMart UAE - Update Orders with Totals
# ==========================================

import pandas as pd

orders = pd.read_csv("orders.csv")
order_items = pd.read_csv("order_items.csv")

# Calculate totals for each order
order_summary = (
    order_items
    .groupby("order_id")
    .agg(
        total_items=("quantity", "sum"),
        total_discount=("discount_amount", "sum"),
        order_total=("line_total", "sum")
    )
    .reset_index()
)

# Merge into orders
orders = orders.merge(
    order_summary,
    on="order_id",
    how="left"
)

# Round values
orders["total_discount"] = orders["total_discount"].round(2)
orders["order_total"] = orders["order_total"].round(2)

# Save updated orders
orders.to_csv("orders.csv", index=False)

print("orders.csv updated successfully!")

orders.head()

orders.csv updated successfully!

,order_id,customer_id,store_id,order_date,delivery_date,order_status,delivery_type,payment_method,shipping_fee,total_items,total_discount,order_total
0,O000001,C05649,ST027,2024-09-20,2024-09-21,Returned,Pickup,Card,0,6,0.88,74.44
1,O000002,C04613,ST023,2026-02-07,2026-02-09,Delivered,Standard,Apple Pay,10,4,0.67,17.78
2,O000003,C06669,ST016,2024-08-30,2024-08-31,Delivered,Pickup,Card,0,1,2.88,11.52
3,O000004,C07999,ST028,2025-03-08,NaN,Processing,Express,Card,25,5,1.52,109.72
4,O000005,C09452,ST012,2026-01-18,2026-01-22,Delivered,Standard,Cash on Delivery,10,5,0.00,54.26

In [66]:
orders = pd.read_csv("orders.csv")

print(orders[[
    "total_items",
    "total_discount",
    "order_total"
]].describe())

orders.head()

        total_items  total_discount   order_total
count  40000.000000    40000.000000  40000.000000
mean       5.267275        4.065435    117.092531
std        3.077698        4.206955     95.736388
min        1.000000        0.000000      1.100000
25%        3.000000        0.980000     46.337500
50%        5.000000        2.840000     94.530000
75%        7.000000        5.830000    160.160000
max       19.000000       43.820000    991.480000

,order_id,customer_id,store_id,order_date,delivery_date,order_status,delivery_type,payment_method,shipping_fee,total_items,total_discount,order_total
0,O000001,C05649,ST027,2024-09-20,2024-09-21,Returned,Pickup,Card,0,6,0.88,74.44
1,O000002,C04613,ST023,2026-02-07,2026-02-09,Delivered,Standard,Apple Pay,10,4,0.67,17.78
2,O000003,C06669,ST016,2024-08-30,2024-08-31,Delivered,Pickup,Card,0,1,2.88,11.52
3,O000004,C07999,ST028,2025-03-08,NaN,Processing,Express,Card,25,5,1.52,109.72
4,O000005,C09452,ST012,2026-01-18,2026-01-22,Delivered,Standard,Cash on Delivery,10,5,0.00,54.26

In [67]:
# ==========================================
# FreshMart UAE - Inventory Generator
# ==========================================

import pandas as pd
import random
from faker import Faker

fake = Faker()

products = pd.read_csv("products.csv")
stores = pd.read_csv("stores.csv")

inventory = []

inventory_counter = 1

for _, store in stores.iterrows():

    for _, product in products.iterrows():

        stock = random.randint(20, 500)

        reorder_level = random.randint(20, 80)

        inventory.append({

            "inventory_id": f"I{inventory_counter:06d}",

            "store_id": store["store_id"],

            "product_id": product["product_id"],

            "current_stock": stock,

            "reorder_level": reorder_level,

            "reorder_status":
                "Yes" if stock <= reorder_level else "No",

            "last_stock_update":
                fake.date_between(
                    start_date="-60d",
                    end_date="today"
                )

        })

        inventory_counter += 1

inventory_df = pd.DataFrame(inventory)

inventory_df.to_csv(
    "inventory.csv",
    index=False
)

print("inventory.csv created successfully")
print("Total Inventory Records:", len(inventory_df))

inventory_df.head()

inventory.csv created successfully
Total Inventory Records: 27000

,inventory_id,store_id,product_id,current_stock,reorder_level,reorder_status,last_stock_update
0,I000001,ST001,P0001,348,33,No,2026-06-17
1,I000002,ST001,P0002,255,54,No,2026-07-23
2,I000003,ST001,P0003,36,80,Yes,2026-06-02
3,I000004,ST001,P0004,128,22,No,2026-07-04
4,I000005,ST001,P0005,248,72,No,2026-06-01

In [68]:
inventory = pd.read_csv("inventory.csv")

print("Total Records:", len(inventory))

print("\nMissing Values:")
print(inventory.isnull().sum())

print("\nDuplicate Inventory IDs:")
print(inventory["inventory_id"].duplicated().sum())

print("\nReorder Status:")
print(inventory["reorder_status"].value_counts())

print("\nCurrent Stock Summary:")
print(inventory["current_stock"].describe())

inventory.head()

Total Records: 27000

Missing Values:
inventory_id         0
store_id             0
product_id           0
current_stock        0
reorder_level        0
reorder_status       0
last_stock_update    0
dtype: int64

Duplicate Inventory IDs:
0

Reorder Status:
reorder_status
No     25273
Yes     1727
Name: count, dtype: int64

Current Stock Summary:
count    27000.000000
mean       261.994037
std        138.673699
min         20.000000
25%        143.000000
50%        263.000000
75%        382.000000
max        500.000000
Name: current_stock, dtype: float64

,inventory_id,store_id,product_id,current_stock,reorder_level,reorder_status,last_stock_update
0,I000001,ST001,P0001,348,33,No,2026-06-17
1,I000002,ST001,P0002,255,54,No,2026-07-23
2,I000003,ST001,P0003,36,80,Yes,2026-06-02
3,I000004,ST001,P0004,128,22,No,2026-07-04
4,I000005,ST001,P0005,248,72,No,2026-06-01

In [69]:
# ==========================================
# FreshMart UAE - Payment Generator
# ==========================================

import pandas as pd
import random
from faker import Faker

fake = Faker()

orders = pd.read_csv("orders.csv")

payments = []

payment_counter = 1

for _, order in orders.iterrows():

    if order["order_status"] == "Cancelled":
        payment_status = "Refunded"

    else:
        payment_status = random.choices(
            ["Paid", "Pending"],
            weights=[97, 3]
        )[0]

    payment_amount = round(
        order["order_total"] + order["shipping_fee"],
        2
    )

    payments.append({

        "payment_id": f"PAY{payment_counter:06d}",

        "order_id": order["order_id"],

        "payment_method": order["payment_method"],

        "payment_amount": payment_amount,

        "payment_status": payment_status,

        "payment_date": order["order_date"]

    })

    payment_counter += 1

payments_df = pd.DataFrame(payments)

payments_df.to_csv(
    "payments.csv",
    index=False
)

print("payments.csv created successfully")
print("Total Payments:", len(payments_df))

payments_df.head()

payments.csv created successfully
Total Payments: 40000

,payment_id,order_id,payment_method,payment_amount,payment_status,payment_date
0,PAY000001,O000001,Card,74.44,Paid,2024-09-20
1,PAY000002,O000002,Apple Pay,27.78,Paid,2026-02-07
2,PAY000003,O000003,Card,11.52,Paid,2024-08-30
3,PAY000004,O000004,Card,134.72,Paid,2025-03-08
4,PAY000005,O000005,Cash on Delivery,64.26,Paid,2026-01-18

In [70]:
payments = pd.read_csv("payments.csv")

print("Total Payments:", len(payments))

print("\nMissing Values:")
print(payments.isnull().sum())

print("\nDuplicate Payment IDs:")
print(payments["payment_id"].duplicated().sum())

print("\nPayment Status:")
print(payments["payment_status"].value_counts())

print("\nPayment Method:")
print(payments["payment_method"].value_counts())

print("\nPayment Amount Summary:")
print(payments["payment_amount"].describe())

payments.head()

Total Payments: 40000

Missing Values:
payment_id        0
order_id          0
payment_method    0
payment_amount    0
payment_status    0
payment_date      0
dtype: int64

Duplicate Payment IDs:
0

Payment Status:
payment_status
Paid        36849
Refunded     1971
Pending      1180
Name: count, dtype: int64

Payment Method:
payment_method
Card                17994
Cash on Delivery     8194
Apple Pay            5931
Wallet               3968
Google Pay           3913
Name: count, dtype: int64

Payment Amount Summary:
count    40000.000000
mean       129.090031
std         96.014979
min          1.560000
25%         58.387500
50%        106.790000
75%        172.540000
max       1008.110000
Name: payment_amount, dtype: float64

,payment_id,order_id,payment_method,payment_amount,payment_status,payment_date
0,PAY000001,O000001,Card,74.44,Paid,2024-09-20
1,PAY000002,O000002,Apple Pay,27.78,Paid,2026-02-07
2,PAY000003,O000003,Card,11.52,Paid,2024-08-30
3,PAY000004,O000004,Card,134.72,Paid,2025-03-08
4,PAY000005,O000005,Cash on Delivery,64.26,Paid,2026-01-18

In [72]:
# ==========================================
# FreshMart UAE - Returns Generator
# ==========================================

import pandas as pd
import random

orders = pd.read_csv("orders.csv")

# Only returned orders
returned_orders = orders[
    orders["order_status"] == "Returned"
].copy()

return_reasons = [
    "Damaged Product",
    "Wrong Item",
    "Expired Product",
    "Poor Quality",
    "Customer Changed Mind",
    "Missing Items"
]

return_statuses = [
    "Approved",
    "Rejected",
    "Refund Completed"
]

returns = []

return_counter = 1

for _, order in returned_orders.iterrows():

    delivery_date = pd.to_datetime(order["delivery_date"])

    # Return created 1–15 days after delivery
    return_date = (
        delivery_date +
        pd.Timedelta(days=random.randint(1, 15))
    ).date()

    returns.append({

        "return_id": f"R{return_counter:06d}",

        "order_id": order["order_id"],

        "customer_id": order["customer_id"],

        "return_date": return_date,

        "return_reason": random.choice(return_reasons),

        "return_status": random.choices(
            return_statuses,
            weights=[40, 10, 50],
            k=1
        )[0]

    })

    return_counter += 1

returns_df = pd.DataFrame(returns)

returns_df.to_csv(
    "returns.csv",
    index=False
)

print("returns.csv created successfully")
print("Total Returns:", len(returns_df))

returns_df.head()

returns.csv created successfully
Total Returns: 2382

,return_id,order_id,customer_id,return_date,return_reason,return_status
0,R000001,O000001,C05649,2024-10-02,Missing Items,Refund Completed
1,R000002,O000046,C05977,2025-01-09,Poor Quality,Refund Completed
2,R000003,O000061,C03544,2026-03-12,Damaged Product,Approved
3,R000004,O000067,C09926,2024-10-23,Wrong Item,Approved
4,R000005,O000072,C06935,2026-07-02,Customer Changed Mind,Approved

In [73]:
# ==========================================
# FreshMart UAE - Promotions Generator
# ==========================================

import pandas as pd
import random
from faker import Faker

fake = Faker()

products = pd.read_csv("products.csv")

NUM_PROMOTIONS = 100

promotion_names = [
    "Weekend Sale",
    "Mega Discount",
    "Ramadan Offer",
    "Summer Sale",
    "Buy More Save More",
    "Family Pack Offer",
    "Flash Sale",
    "Festive Offer",
    "Loyalty Bonus",
    "New Arrival Offer"
]

promotions = []

for i in range(1, NUM_PROMOTIONS + 1):

    product = products.sample(1).iloc[0]

    start_date = fake.date_between(
        start_date="-2y",
        end_date="today"
    )

    duration = random.randint(7, 30)

    end_date = (
        pd.to_datetime(start_date) +
        pd.Timedelta(days=duration)
    ).date()

    discount = random.choice(
        [5, 10, 15, 20, 25, 30]
    )

    promotions.append({

        "promotion_id": f"PR{i:04d}",

        "promotion_name": random.choice(
            promotion_names
        ),

        "product_id": product["product_id"],

        "discount_percent": discount,

        "start_date": start_date,

        "end_date": end_date,

        "status": random.choices(
            ["Active", "Expired"],
            weights=[20, 80],
            k=1
        )[0]

    })

promotions_df = pd.DataFrame(promotions)

promotions_df.to_csv(
    "promotions.csv",
    index=False
)

print("promotions.csv created successfully")
print("Total Promotions:", len(promotions_df))

promotions_df.head()

promotions.csv created successfully
Total Promotions: 100

,promotion_id,promotion_name,product_id,discount_percent,start_date,end_date,status
0,PR0001,Summer Sale,P0056,30,2025-03-22,2025-03-30,Expired
1,PR0002,Ramadan Offer,P0099,15,2025-03-27,2025-04-18,Expired
2,PR0003,Ramadan Offer,P0072,15,2026-02-15,2026-03-01,Expired
3,PR0004,Ramadan Offer,P0360,15,2025-06-29,2025-07-25,Expired
4,PR0005,Buy More Save More,P0090,25,2024-09-19,2024-10-02,Expired

In [74]:
promotions = pd.read_csv("promotions.csv")

print("Total Promotions:", len(promotions))

print("\nMissing Values:")
print(promotions.isnull().sum())

print("\nDuplicate Promotion IDs:")
print(promotions["promotion_id"].duplicated().sum())

print("\nPromotion Status:")
print(promotions["status"].value_counts())

print("\nDiscount Distribution:")
print(promotions["discount_percent"].value_counts().sort_index())

promotions.head()

Total Promotions: 100

Missing Values:
promotion_id        0
promotion_name      0
product_id          0
discount_percent    0
start_date          0
end_date            0
status              0
dtype: int64

Duplicate Promotion IDs:
0

Promotion Status:
status
Expired    84
Active     16
Name: count, dtype: int64

Discount Distribution:
discount_percent
5     18
10    16
15    23
20    15
25    14
30    14
Name: count, dtype: int64

,promotion_id,promotion_name,product_id,discount_percent,start_date,end_date,status
0,PR0001,Summer Sale,P0056,30,2025-03-22,2025-03-30,Expired
1,PR0002,Ramadan Offer,P0099,15,2025-03-27,2025-04-18,Expired
2,PR0003,Ramadan Offer,P0072,15,2026-02-15,2026-03-01,Expired
3,PR0004,Ramadan Offer,P0360,15,2025-06-29,2025-07-25,Expired
4,PR0005,Buy More Save More,P0090,25,2024-09-19,2024-10-02,Expired

In [75]:
# ==========================================
# FreshMart UAE - Reviews Generator
# ==========================================

import pandas as pd
import random
from faker import Faker

fake = Faker()

orders = pd.read_csv("orders.csv")

# Only delivered orders
delivered_orders = orders[
    orders["order_status"] == "Delivered"
].copy()

# Around 40% of delivered orders leave a review
reviews_orders = delivered_orders.sample(
    frac=0.40,
    random_state=42
)

review_comments = {
    5: [
        "Excellent quality",
        "Highly recommended",
        "Very satisfied",
        "Fresh products",
        "Fast delivery"
    ],
    4: [
        "Good service",
        "Nice packaging",
        "Value for money",
        "Satisfied"
    ],
    3: [
        "Average experience",
        "Delivery was okay",
        "Could be better"
    ],
    2: [
        "Late delivery",
        "Packaging issue",
        "Product quality below expectations"
    ],
    1: [
        "Very disappointed",
        "Wrong item received",
        "Damaged product"
    ]
}

ratings = [5, 4, 3, 2, 1]
rating_weights = [55, 25, 10, 6, 4]

reviews = []

review_counter = 1

for _, order in reviews_orders.iterrows():

    rating = random.choices(
        ratings,
        weights=rating_weights,
        k=1
    )[0]

    review_date = (
        pd.to_datetime(order["delivery_date"])
        + pd.Timedelta(days=random.randint(1, 10))
    ).date()

    reviews.append({

        "review_id": f"RV{review_counter:06d}",

        "order_id": order["order_id"],

        "customer_id": order["customer_id"],

        "rating": rating,

        "review_comment": random.choice(
            review_comments[rating]
        ),

        "review_date": review_date

    })

    review_counter += 1

reviews_df = pd.DataFrame(reviews)

reviews_df.to_csv(
    "reviews.csv",
    index=False
)

print("reviews.csv created successfully")
print("Total Reviews:", len(reviews_df))

reviews_df.head()

reviews.csv created successfully
Total Reviews: 13611

  review_id order_id customer_id  rating      review_comment review_date
0  RV000001  O020021      C05534       5       Fast delivery  2025-08-22
1  RV000002  O006481      C02017       5  Highly recommended  2025-10-18
2  RV000003  O010872      C04459       3   Delivery was okay  2026-02-01
3  RV000004  O006844      C05759       4        Good service  2025-12-21
4  RV000005  O000411      C03733       4     Value for money  2025-05-29

In [76]:
reviews = pd.read_csv("reviews.csv")

print("Total Reviews:", len(reviews))

print("\nMissing Values:")
print(reviews.isnull().sum())

print("\nDuplicate Review IDs:")
print(reviews["review_id"].duplicated().sum())

print("\nRating Distribution:")
print(reviews["rating"].value_counts().sort_index())

print("\nAverage Rating:")
print(round(reviews["rating"].mean(), 2))

reviews.head()

Total Reviews: 13611

Missing Values:
review_id         0
order_id          0
customer_id       0
rating            0
review_comment    0
review_date       0
dtype: int64

Duplicate Review IDs:
0

Rating Distribution:
rating
1     488
2     813
3    1317
4    3470
5    7523
Name: count, dtype: int64

Average Rating:
4.23

  review_id order_id customer_id  rating      review_comment review_date
0  RV000001  O020021      C05534       5       Fast delivery  2025-08-22
1  RV000002  O006481      C02017       5  Highly recommended  2025-10-18
2  RV000003  O010872      C04459       3   Delivery was okay  2026-02-01
3  RV000004  O006844      C05759       4        Good service  2025-12-21
4  RV000005  O000411      C03733       4     Value for money  2025-05-29

In [77]:
# ==========================================
# FreshMart UAE - QA Step 1
# Master Tables
# ==========================================

import pandas as pd

customers = pd.read_csv("customers.csv")
products = pd.read_csv("products.csv")
suppliers = pd.read_csv("suppliers.csv")
stores = pd.read_csv("stores.csv")
employees = pd.read_csv("employees.csv")

tables = {
    "Customers": (customers, "customer_id"),
    "Products": (products, "product_id"),
    "Suppliers": (suppliers, "supplier_id"),
    "Stores": (stores, "store_id"),
    "Employees": (employees, "employee_id")
}

for name, (df, pk) in tables.items():

    print("=" * 50)
    print(name.upper())

    print("Rows:", len(df))

    print("Missing Values:")
    print(df.isnull().sum().sum())

    print("Duplicate Primary Keys:")
    print(df[pk].duplicated().sum())

    print()

==================================================
CUSTOMERS
Rows: 10000
Missing Values:
0
Duplicate Primary Keys:
0

==================================================
PRODUCTS
Rows: 900
Missing Values:
0
Duplicate Primary Keys:
0

==================================================
SUPPLIERS
Rows: 100
Missing Values:
0
Duplicate Primary Keys:
0

==================================================
STORES
Rows: 30
Missing Values:
0
Duplicate Primary Keys:
0

==================================================
EMPLOYEES
Rows: 150
Missing Values:
0
Duplicate Primary Keys:
0

In [78]:
# ==========================================
# FreshMart UAE - QA Step 2
# Foreign Key Validation
# ==========================================

orders = pd.read_csv("orders.csv")
order_items = pd.read_csv("order_items.csv")
payments = pd.read_csv("payments.csv")
returns = pd.read_csv("returns.csv")
reviews = pd.read_csv("reviews.csv")
inventory = pd.read_csv("inventory.csv")

print("Orders -> Customers")
print(
    orders["customer_id"].isin(
        customers["customer_id"]
    ).all()
)

print()

print("Orders -> Stores")
print(
    orders["store_id"].isin(
        stores["store_id"]
    ).all()
)

print()

print("Order Items -> Orders")
print(
    order_items["order_id"].isin(
        orders["order_id"]
    ).all()
)

print()

print("Order Items -> Products")
print(
    order_items["product_id"].isin(
        products["product_id"]
    ).all()
)

print()

print("Payments -> Orders")
print(
    payments["order_id"].isin(
        orders["order_id"]
    ).all()
)

print()

print("Returns -> Orders")
print(
    returns["order_id"].isin(
        orders["order_id"]
    ).all()
)

print()

print("Reviews -> Orders")
print(
    reviews["order_id"].isin(
        orders["order_id"]
    ).all()
)

print()

print("Inventory -> Products")
print(
    inventory["product_id"].isin(
        products["product_id"]
    ).all()
)

print()

print("Inventory -> Stores")
print(
    inventory["store_id"].isin(
        stores["store_id"]
    ).all()
)

Orders -> Customers
True

Orders -> Stores
True

Order Items -> Orders
True

Order Items -> Products
True

Payments -> Orders
True

Returns -> Orders
True

Reviews -> Orders
True

Inventory -> Products
True

Inventory -> Stores
True

In [79]:
# ==========================================
# FreshMart UAE - QA Step 3
# Business Logic Validation
# ==========================================

import pandas as pd

orders = pd.read_csv("orders.csv")
payments = pd.read_csv("payments.csv")
returns = pd.read_csv("returns.csv")
reviews = pd.read_csv("reviews.csv")
inventory = pd.read_csv("inventory.csv")
promotions = pd.read_csv("promotions.csv")

print("=" * 60)
print("BUSINESS LOGIC VALIDATION")
print("=" * 60)

# -------------------------------------------------
# 1. Payment Amount Check
# -------------------------------------------------
merged = orders.merge(
    payments,
    on="order_id",
    suffixes=("_order", "_payment")
)

payment_check = (
    (merged["order_total"] + merged["shipping_fee"]).round(2)
    == merged["payment_amount"].round(2)
).all()

print("\n1. Payment Amount Validation:", payment_check)

# -------------------------------------------------
# 2. Returned Orders Check
# -------------------------------------------------
returned_orders = set(
    orders.loc[
        orders["order_status"] == "Returned",
        "order_id"
    ]
)

returns_check = set(
    returns["order_id"]
).issubset(returned_orders)

print("2. Returns Validation:", returns_check)

# -------------------------------------------------
# 3. Reviews Check
# -------------------------------------------------
delivered_orders = set(
    orders.loc[
        orders["order_status"] == "Delivered",
        "order_id"
    ]
)

reviews_check = set(
    reviews["order_id"]
).issubset(delivered_orders)

print("3. Reviews Validation:", reviews_check)

# -------------------------------------------------
# 4. Inventory Check
# -------------------------------------------------
inventory_check = (
    (
        (inventory["current_stock"] <= inventory["reorder_level"])
        ==
        (inventory["reorder_status"] == "Yes")
    )
).all()

print("4. Inventory Reorder Logic:", inventory_check)

# -------------------------------------------------
# 5. Promotion Dates
# -------------------------------------------------
promotions["start_date"] = pd.to_datetime(promotions["start_date"])
promotions["end_date"] = pd.to_datetime(promotions["end_date"])

promotion_check = (
    promotions["end_date"] >= promotions["start_date"]
).all()

print("5. Promotion Dates:", promotion_check)

print("\n" + "=" * 60)
print("QA COMPLETED")
print("=" * 60)

============================================================
BUSINESS LOGIC VALIDATION
============================================================

1. Payment Amount Validation: True
2. Returns Validation: True
3. Reviews Validation: True
4. Inventory Reorder Logic: True
5. Promotion Dates: True

============================================================
QA COMPLETED
============================================================

In [80]:
# ==========================================
# FreshMart UAE - Link Products to Suppliers
# ==========================================

import pandas as pd
import random

products = pd.read_csv("products.csv")
suppliers = pd.read_csv("suppliers.csv")

# Dictionary: Category -> Supplier IDs
supplier_lookup = (
    suppliers
    .groupby("category")["supplier_id"]
    .apply(list)
    .to_dict()
)

# Assign supplier based on product category
products["supplier_id"] = products["category"].apply(
    lambda category: random.choice(supplier_lookup[category])
)

# Save updated products
products.to_csv("products.csv", index=False)

print("products.csv updated successfully!")

products.head()

products.csv updated successfully!

,product_id,product_name,category,sub_category,brand,size,unit_cost,selling_price,profit_margin,barcode,expiry_required,launch_date,status,supplier_id
0,P0001,FreshMart Lemon Dishwash 500ml,Cleaning Supplies,Dishwashing Liquid,FreshMart,500ml,20.94,27.62,24.19,2750732794002,No,2024-08-11,Active,S0076
1,P0002,McVitie's Chocolate Biscuits 250g,Snacks,Biscuits,McVitie's,250g,7.73,9.97,22.47,4157447233099,No,2025-06-06,Active,S0008
2,P0003,Cerelac Baby Formula 400g,Baby Care,Baby Food,Cerelac,400g,24.86,36.04,31.02,330867318711,Yes,2022-02-13,Active,S0014
3,P0004,FreshMart Digestive Biscuits 250g,Snacks,Biscuits,FreshMart,250g,7.45,11.20,33.48,5671848434200,No,2024-05-31,Active,S0008
4,P0005,FreshMart Disinfectant Floor Cleaner 1L,Cleaning Supplies,Floor Cleaner,FreshMart,1L,22.38,32.72,31.60,8934060730190,No,2025-05-11,Active,S0076

In [81]:
products = pd.read_csv("products.csv")
suppliers = pd.read_csv("suppliers.csv")

print("Missing Supplier IDs:")
print(products["supplier_id"].isnull().sum())

print("\nInvalid Supplier IDs:")
print(
    (~products["supplier_id"].isin(suppliers["supplier_id"])).sum()
)

print("\nProducts per Supplier:")
print(products["supplier_id"].value_counts().head(10))

products.head()

Missing Supplier IDs:
0

Invalid Supplier IDs:
0

Products per Supplier:
supplier_id
S0008    92
S0089    92
S0080    16
S0062    16
S0061    14
S0036    14
S0055    14
S0045    13
S0075    13
S0032    13
Name: count, dtype: int64

,product_id,product_name,category,sub_category,brand,size,unit_cost,selling_price,profit_margin,barcode,expiry_required,launch_date,status,supplier_id
0,P0001,FreshMart Lemon Dishwash 500ml,Cleaning Supplies,Dishwashing Liquid,FreshMart,500ml,20.94,27.62,24.19,2750732794002,No,2024-08-11,Active,S0076
1,P0002,McVitie's Chocolate Biscuits 250g,Snacks,Biscuits,McVitie's,250g,7.73,9.97,22.47,4157447233099,No,2025-06-06,Active,S0008
2,P0003,Cerelac Baby Formula 400g,Baby Care,Baby Food,Cerelac,400g,24.86,36.04,31.02,330867318711,Yes,2022-02-13,Active,S0014
3,P0004,FreshMart Digestive Biscuits 250g,Snacks,Biscuits,FreshMart,250g,7.45,11.20,33.48,5671848434200,No,2024-05-31,Active,S0008
4,P0005,FreshMart Disinfectant Floor Cleaner 1L,Cleaning Supplies,Floor Cleaner,FreshMart,1L,22.38,32.72,31.60,8934060730190,No,2025-05-11,Active,S0076

In [82]:
# ==========================================
# FreshMart UAE - Link Store Managers
# ==========================================

import pandas as pd

stores = pd.read_csv("stores.csv")
employees = pd.read_csv("employees.csv")

# Get only Store Managers
store_managers = employees[
    employees["job_role"] == "Store Manager"
].copy()

# Keep one manager per store
manager_lookup = (
    store_managers
    .drop_duplicates(subset="store_id")
    .set_index("store_id")["employee_id"]
)

# Assign manager_id to each store
stores["manager_id"] = stores["store_id"].map(manager_lookup)

# Save updated stores table
stores.to_csv("stores.csv", index=False)

print("stores.csv updated successfully!")

stores.head()

stores.csv updated successfully!

,store_id,store_name,store_type,city,emirate,store_size_sqft,daily_customer_capacity,opening_date,store_manager,status,manager_id
0,ST001,FreshMart Dubai 1,Supermarket,Dubai,Dubai,1627,2206,2020-04-29,Jessica Baldwin,Active,NaN
1,ST002,FreshMart Dubai 2,Supermarket,Dubai,Dubai,1888,1206,2015-12-13,Becky Mcbride,Renovation,NaN
2,ST003,FreshMart Dubai 3,Hypermarket,Dubai,Dubai,4246,3923,2014-09-11,Janet Park,Active,E0007
3,ST004,FreshMart Dubai 4,Supermarket,Dubai,Dubai,3110,1450,2021-01-07,Leslie Holmes,Active,NaN
4,ST005,FreshMart Dubai 5,Express,Dubai,Dubai,611,408,2022-10-18,Joseph Mccormick,Active,E0079

In [83]:
stores = pd.read_csv("stores.csv")
employees = pd.read_csv("employees.csv")

print("Missing Manager IDs:")
print(stores["manager_id"].isnull().sum())

print("\nInvalid Manager IDs:")
print(
    (~stores["manager_id"].isin(employees["employee_id"])).sum()
)

stores.head()

Missing Manager IDs:
20

Invalid Manager IDs:
20

,store_id,store_name,store_type,city,emirate,store_size_sqft,daily_customer_capacity,opening_date,store_manager,status,manager_id
0,ST001,FreshMart Dubai 1,Supermarket,Dubai,Dubai,1627,2206,2020-04-29,Jessica Baldwin,Active,NaN
1,ST002,FreshMart Dubai 2,Supermarket,Dubai,Dubai,1888,1206,2015-12-13,Becky Mcbride,Renovation,NaN
2,ST003,FreshMart Dubai 3,Hypermarket,Dubai,Dubai,4246,3923,2014-09-11,Janet Park,Active,E0007
3,ST004,FreshMart Dubai 4,Supermarket,Dubai,Dubai,3110,1450,2021-01-07,Leslie Holmes,Active,NaN
4,ST005,FreshMart Dubai 5,Express,Dubai,Dubai,611,408,2022-10-18,Joseph Mccormick,Active,E0079

In [84]:
# ==========================================
# FreshMart UAE - Fix Store Manager Mapping
# ==========================================

import pandas as pd

stores = pd.read_csv("stores.csv")
employees = pd.read_csv("employees.csv")

# Priority of roles
priority_roles = [
    "Store Manager",
    "Assistant Manager",
    "Supervisor"
]

manager_lookup = {}

# Find one manager for each store based on priority
for store in stores["store_id"]:

    selected_manager = None

    for role in priority_roles:

        emp = employees[
            (employees["store_id"] == store) &
            (employees["job_role"] == role)
        ]

        if not emp.empty:
            selected_manager = emp.iloc[0]["employee_id"]
            break

    manager_lookup[store] = selected_manager

# Update manager_id
stores["manager_id"] = stores["store_id"].map(manager_lookup)

# Save
stores.to_csv("stores.csv", index=False)

print("stores.csv updated successfully!")

stores.head()

stores.csv updated successfully!

,store_id,store_name,store_type,city,emirate,store_size_sqft,daily_customer_capacity,opening_date,store_manager,status,manager_id
0,ST001,FreshMart Dubai 1,Supermarket,Dubai,Dubai,1627,2206,2020-04-29,Jessica Baldwin,Active,E0083
1,ST002,FreshMart Dubai 2,Supermarket,Dubai,Dubai,1888,1206,2015-12-13,Becky Mcbride,Renovation,E0096
2,ST003,FreshMart Dubai 3,Hypermarket,Dubai,Dubai,4246,3923,2014-09-11,Janet Park,Active,E0007
3,ST004,FreshMart Dubai 4,Supermarket,Dubai,Dubai,3110,1450,2021-01-07,Leslie Holmes,Active,E0004
4,ST005,FreshMart Dubai 5,Express,Dubai,Dubai,611,408,2022-10-18,Joseph Mccormick,Active,E0079

In [85]:
stores = pd.read_csv("stores.csv")
employees = pd.read_csv("employees.csv")

print("Missing Manager IDs:")
print(stores["manager_id"].isnull().sum())

print()

print("Invalid Manager IDs:")
print(
    (~stores["manager_id"].isin(employees["employee_id"])).sum()
)

Missing Manager IDs:
4

Invalid Manager IDs:
4

In [86]:
stores = pd.read_csv("stores.csv")

missing_stores = stores[
    stores["manager_id"].isnull()
]

print(missing_stores[["store_id", "store_name"]])

   store_id             store_name
5     ST006      FreshMart Dubai 6
10    ST011  FreshMart Abu Dhabi 1
20    ST021    FreshMart Sharjah 5
29    ST030     FreshMart Al Ain 2

In [87]:
employees = pd.read_csv("employees.csv")

employees[
    employees["store_id"].isin(missing_stores["store_id"])
].sort_values(["store_id", "job_role"])

,employee_id,employee_name,gender,age,job_role,store_id,store_name,hire_date,salary,status
137,E0138,Ronald Baird,Male,54,Inventory Associate,ST006,FreshMart Dubai 6,2021-03-27,4456,Active
79,E0080,Ana Miller,Female,31,Cashier,ST011,FreshMart Abu Dhabi 1,2024-04-15,3218,Active
104,E0105,Colton Miller,Male,55,Cashier,ST011,FreshMart Abu Dhabi 1,2024-12-19,4176,Active
16,E0017,Pamela Montgomery,Male,27,Customer Service Executive,ST011,FreshMart Abu Dhabi 1,2019-12-23,3929,Active
47,E0048,Mark Richardson,Male,32,Customer Service Executive,ST011,FreshMart Abu Dhabi 1,2019-07-23,4641,Active
81,E0082,Jeff Johnson,Male,37,Customer Service Executive,ST011,FreshMart Abu Dhabi 1,2024-09-28,4212,Active
12,E0013,Mason Bates,Female,50,Inventory Associate,ST011,FreshMart Abu Dhabi 1,2023-09-15,4593,Active
28,E0029,Nathan Serrano,Female,45,Cashier,ST021,FreshMart Sharjah 5,2021-12-07,4091,Active
91,E0092,Donna Jordan,Male,27,Cashier,ST021,FreshMart Sharjah 5,2021-11-30,3034,On Leave
119,E0120,Charles Smith,Female,57,Cashier,ST030,FreshMart Al Ain 2,2024-01-16,3719,Active

In [88]:
# ==========================================
# FreshMart UAE - Fix Missing Supervisors
# ==========================================

import pandas as pd

employees = pd.read_csv("employees.csv")

# Promote selected employees
employees.loc[
    employees["employee_id"] == "E0138",
    "job_role"
] = "Supervisor"

employees.loc[
    employees["employee_id"] == "E0017",
    "job_role"
] = "Supervisor"

employees.loc[
    employees["employee_id"] == "E0029",
    "job_role"
] = "Supervisor"

employees.loc[
    employees["employee_id"] == "E0120",
    "job_role"
] = "Supervisor"

employees.to_csv("employees.csv", index=False)

print("employees.csv updated successfully!")

employees.csv updated successfully!

In [90]:
# ==========================================
# FreshMart UAE - Fix Store Manager Mapping
# ==========================================

import pandas as pd

stores = pd.read_csv("stores.csv")
employees = pd.read_csv("employees.csv")

# Priority of roles
priority_roles = [
    "Store Manager",
    "Assistant Manager",
    "Supervisor"
]

manager_lookup = {}

# Find one manager for each store based on priority
for store in stores["store_id"]:

    selected_manager = None

    for role in priority_roles:

        emp = employees[
            (employees["store_id"] == store) &
            (employees["job_role"] == role)
        ]

        if not emp.empty:
            selected_manager = emp.iloc[0]["employee_id"]
            break

    manager_lookup[store] = selected_manager

# Update manager_id
stores["manager_id"] = stores["store_id"].map(manager_lookup)

# Save updated stores table
stores.to_csv("stores.csv", index=False)

print("stores.csv updated successfully!")

stores.head()

stores.csv updated successfully!

,store_id,store_name,store_type,city,emirate,store_size_sqft,daily_customer_capacity,opening_date,store_manager,status,manager_id
0,ST001,FreshMart Dubai 1,Supermarket,Dubai,Dubai,1627,2206,2020-04-29,Jessica Baldwin,Active,E0083
1,ST002,FreshMart Dubai 2,Supermarket,Dubai,Dubai,1888,1206,2015-12-13,Becky Mcbride,Renovation,E0096
2,ST003,FreshMart Dubai 3,Hypermarket,Dubai,Dubai,4246,3923,2014-09-11,Janet Park,Active,E0007
3,ST004,FreshMart Dubai 4,Supermarket,Dubai,Dubai,3110,1450,2021-01-07,Leslie Holmes,Active,E0004
4,ST005,FreshMart Dubai 5,Express,Dubai,Dubai,611,408,2022-10-18,Joseph Mccormick,Active,E0079

In [91]:
stores = pd.read_csv("stores.csv")
employees = pd.read_csv("employees.csv")

print("Missing Manager IDs:")
print(stores["manager_id"].isnull().sum())

print("\nInvalid Manager IDs:")
print((~stores["manager_id"].isin(employees["employee_id"])).sum())

Missing Manager IDs:
0

Invalid Manager IDs:
0

In [12]:
# ==========================================
# FreshMart UAE - FINAL DATASET QA REPORT
# ==========================================

import pandas as pd

print("=" * 70)
print("           FRESHMART UAE - FINAL DATASET QA REPORT")
print("=" * 70)

# --------------------------------------------------
# Load Tables
# --------------------------------------------------
customers = pd.read_csv("customers.csv")
products = pd.read_csv("products.csv")
suppliers = pd.read_csv("suppliers.csv")
stores = pd.read_csv("stores.csv")
employees = pd.read_csv("employees.csv")
orders = pd.read_csv("orders.csv")
order_items = pd.read_csv("order_items.csv")
inventory = pd.read_csv("inventory.csv")
payments = pd.read_csv("payments.csv")
returns = pd.read_csv("returns.csv")
promotions = pd.read_csv("promotions.csv")
reviews = pd.read_csv("reviews.csv")

# --------------------------------------------------
# Convert Dates
# --------------------------------------------------
customers["join_date"] = pd.to_datetime(customers["join_date"])
products["launch_date"] = pd.to_datetime(products["launch_date"])
stores["opening_date"] = pd.to_datetime(stores["opening_date"])
employees["hire_date"] = pd.to_datetime(employees["hire_date"])

orders["order_date"] = pd.to_datetime(orders["order_date"])
orders["delivery_date"] = pd.to_datetime(orders["delivery_date"])

payments["payment_date"] = pd.to_datetime(payments["payment_date"])

returns["return_date"] = pd.to_datetime(returns["return_date"])

reviews["review_date"] = pd.to_datetime(reviews["review_date"])

promotions["start_date"] = pd.to_datetime(promotions["start_date"])
promotions["end_date"] = pd.to_datetime(promotions["end_date"])

inventory["last_stock_update"] = pd.to_datetime(
    inventory["last_stock_update"]
)

today = pd.Timestamp.today().normalize()

print("\nDATE CONSISTENCY CHECKS")
print("-" * 70)

# --------------------------------------------------
# Customer Join Date
# --------------------------------------------------
customer_check = (
    orders.merge(customers, on="customer_id")
    .query("order_date < join_date")
)

print(
    f"Customer joined after placing order: {len(customer_check)}"
)

# --------------------------------------------------
# Product Launch Date
# --------------------------------------------------
product_check = (
    order_items.merge(
        orders[["order_id", "order_date"]],
        on="order_id"
    )
    .merge(
        products[["product_id", "launch_date"]],
        on="product_id"
    )
)

product_check = product_check[
    product_check["order_date"] <
    product_check["launch_date"]
]

print(
    f"Products sold before launch: {len(product_check)}"
)

# --------------------------------------------------
# Store Opening
# --------------------------------------------------
store_check = (
    orders.merge(
        stores[["store_id", "opening_date"]],
        on="store_id"
    )
)

store_check = store_check[
    store_check["order_date"] <
    store_check["opening_date"]
]

print(
    f"Orders before store opening: {len(store_check)}"
)

# --------------------------------------------------
# Employee Hire Date
# --------------------------------------------------
future_hires = employees[
    employees["hire_date"] > today
]

print(
    f"Employees hired in the future: {len(future_hires)}"
)

# --------------------------------------------------
# Delivery Date
# --------------------------------------------------
delivery_check = orders[
    (orders["delivery_date"].notna()) &
    (orders["delivery_date"] < orders["order_date"])
]

print(
    f"Delivery before order: {len(delivery_check)}"
)

# --------------------------------------------------
# Payment Date
# --------------------------------------------------
payment_check = (
    payments.merge(
        orders[["order_id", "order_date"]],
        on="order_id"
    )
)

payment_check = payment_check[
    payment_check["payment_date"] <
    payment_check["order_date"]
]

print(
    f"Payment before order: {len(payment_check)}"
)

# --------------------------------------------------
# Return Date
# --------------------------------------------------
return_check = (
    returns.merge(
        orders[["order_id", "delivery_date"]],
        on="order_id"
    )
)

return_check = return_check[
    return_check["return_date"] <
    return_check["delivery_date"]
]

print(
    f"Return before delivery: {len(return_check)}"
)

# --------------------------------------------------
# Review Date
# --------------------------------------------------
review_check = (
    reviews.merge(
        orders[["order_id", "delivery_date"]],
        on="order_id"
    )
)

review_check = review_check[
    review_check["review_date"] <
    review_check["delivery_date"]
]

print(
    f"Review before delivery: {len(review_check)}"
)

# --------------------------------------------------
# Promotion Dates
# --------------------------------------------------
promotion_check = promotions[
    promotions["end_date"] < promotions["start_date"]
]

print(
    f"Promotion end before start: {len(promotion_check)}"
)

# --------------------------------------------------
# Inventory Dates
# --------------------------------------------------
inventory_future = inventory[
    inventory["last_stock_update"] > today
]

print(
    f"Future inventory updates: {len(inventory_future)}"
)

print("\n" + "=" * 70)

total_errors = (
    len(customer_check)
    + len(product_check)
    + len(store_check)
    + len(future_hires)
    + len(delivery_check)
    + len(payment_check)
    + len(return_check)
    + len(review_check)
    + len(promotion_check)
    + len(inventory_future)
)

if total_errors == 0:
    print("🎉 FINAL RESULT: DATASET PASSED ALL QA CHECKS")
else:
    print(f"⚠️ FINAL RESULT: {total_errors} ISSUE(S) FOUND")

print("=" * 70)

======================================================================
           FRESHMART UAE - FINAL DATASET QA REPORT
======================================================================

DATE CONSISTENCY CHECKS
----------------------------------------------------------------------
Customer joined after placing order: 0
Products sold before launch: 0
Orders before store opening: 0
Employees hired in the future: 0
Delivery before order: 0
Payment before order: 0
Return before delivery: 0
Review before delivery: 0
Promotion end before start: 0
Future inventory updates: 0

======================================================================
🎉 FINAL RESULT: DATASET PASSED ALL QA CHECKS
======================================================================

In [2]:
import os

print("Current Working Directory:")
print(os.getcwd())

print("\nFiles/Folders:")
print(os.listdir())

Current Working Directory:
D:\MY_DOCUMENT_MAIN_DATA\Desktop\FreshMart UAE

Files/Folders:
['.ipynb_checkpoints', 'customers.csv', 'employees.csv', 'FreshMart_Dataset_Generator - Copy.ipynb', 'FreshMart_Dataset_Generator.ipynb', 'inventory.csv', 'orders.csv', 'order_items.csv', 'payments.csv', 'products.csv', 'promotions.csv', 'Raw data', 'returns.csv', 'reviews.csv', 'stores.csv', 'suppliers.csv']

In [5]:
# ==========================================
# FreshMart UAE - Fix Customer Join Dates
# Compatible with Python 3.14 + Pandas
# ==========================================

import pandas as pd
import random

# Load files
customers = pd.read_csv("customers.csv")
orders = pd.read_csv("orders.csv")

# Convert dates
customers["join_date"] = pd.to_datetime(customers["join_date"])
orders["order_date"] = pd.to_datetime(orders["order_date"])

# Get each customer's first order date
first_orders = (
    orders.groupby("customer_id", as_index=False)["order_date"]
    .min()
    .rename(columns={"order_date": "first_order_date"})
)

# Merge into customer table
customers = customers.merge(first_orders, on="customer_id", how="left")

# Find invalid customers
mask = (
    customers["first_order_date"].notna() &
    (customers["join_date"] > customers["first_order_date"])
)

print("Customers to fix:", mask.sum())

# Fix dates
for idx in customers[mask].index:

    first_order = customers.loc[idx, "first_order_date"]

    days_before = random.randint(30, 730)

    customers.loc[idx, "join_date"] = (
        first_order - pd.Timedelta(days=days_before)
    )

# Remove helper column
customers.drop(columns="first_order_date", inplace=True)

# Save
customers.to_csv("customers.csv", index=False)

print("customers.csv updated successfully!")

Customers to fix: 2971
customers.csv updated successfully!

In [6]:
import pandas as pd

customers = pd.read_csv("customers.csv")
orders = pd.read_csv("orders.csv")

customers["join_date"] = pd.to_datetime(customers["join_date"])
orders["order_date"] = pd.to_datetime(orders["order_date"])

check = orders.merge(customers, on="customer_id")

invalid = check[
    check["order_date"] < check["join_date"]
]

print("Customer joined after placing order:", len(invalid))

Customer joined after placing order: 0

In [8]:
# ==========================================
# FreshMart UAE - Fix Product Launch Dates
# Compatible with Python 3.14 + Pandas
# ==========================================

import pandas as pd
import random

# Load files
products = pd.read_csv("products.csv")
orders = pd.read_csv("orders.csv")
order_items = pd.read_csv("order_items.csv")

# Convert dates
products["launch_date"] = pd.to_datetime(products["launch_date"])
orders["order_date"] = pd.to_datetime(orders["order_date"])

# Find first sale date for every product
first_sales = (
    order_items
    .merge(
        orders[["order_id", "order_date"]],
        on="order_id",
        how="left"
    )
    .groupby("product_id", as_index=False)["order_date"]
    .min()
    .rename(columns={"order_date": "first_sale_date"})
)

# Merge with products
products = products.merge(first_sales, on="product_id", how="left")

# Find invalid products
mask = (
    products["first_sale_date"].notna() &
    (products["launch_date"] > products["first_sale_date"])
)

print("Products to fix:", mask.sum())

# Fix launch dates
for idx in products[mask].index:

    first_sale = products.loc[idx, "first_sale_date"]

    days_before = random.randint(30, 730)

    products.loc[idx, "launch_date"] = (
        first_sale - pd.Timedelta(days=days_before)
    )

# Remove helper column
products.drop(columns="first_sale_date", inplace=True)

# Save
products.to_csv("products.csv", index=False)

print("products.csv updated successfully!")

Products to fix: 361
products.csv updated successfully!

In [9]:
import pandas as pd

products = pd.read_csv("products.csv")
orders = pd.read_csv("orders.csv")
order_items = pd.read_csv("order_items.csv")

products["launch_date"] = pd.to_datetime(products["launch_date"])
orders["order_date"] = pd.to_datetime(orders["order_date"])

check = (
    order_items
    .merge(
        orders[["order_id", "order_date"]],
        on="order_id"
    )
    .merge(
        products[["product_id", "launch_date"]],
        on="product_id"
    )
)

invalid = check[
    check["order_date"] < check["launch_date"]
]

print("Products sold before launch:", len(invalid))

Products sold before launch: 0

In [10]:
# ==========================================
# FreshMart UAE - Fix Store Opening Dates
# Compatible with Python 3.14 + Pandas
# ==========================================

import pandas as pd
import random

# Load files
stores = pd.read_csv("stores.csv")
orders = pd.read_csv("orders.csv")

# Convert dates
stores["opening_date"] = pd.to_datetime(stores["opening_date"])
orders["order_date"] = pd.to_datetime(orders["order_date"])

# First order for each store
first_orders = (
    orders.groupby("store_id", as_index=False)["order_date"]
    .min()
    .rename(columns={"order_date": "first_order_date"})
)

# Merge
stores = stores.merge(first_orders, on="store_id", how="left")

# Find invalid stores
mask = (
    stores["first_order_date"].notna() &
    (stores["opening_date"] > stores["first_order_date"])
)

print("Stores to fix:", mask.sum())

# Fix dates
for idx in stores[mask].index:

    first_order = stores.loc[idx, "first_order_date"]

    days_before = random.randint(30, 730)

    stores.loc[idx, "opening_date"] = (
        first_order - pd.Timedelta(days=days_before)
    )

# Remove helper column
stores.drop(columns="first_order_date", inplace=True)

# Save
stores.to_csv("stores.csv", index=False)

print("stores.csv updated successfully!")

Stores to fix: 6
stores.csv updated successfully!

In [11]:
import pandas as pd

stores = pd.read_csv("stores.csv")
orders = pd.read_csv("orders.csv")

stores["opening_date"] = pd.to_datetime(stores["opening_date"])
orders["order_date"] = pd.to_datetime(orders["order_date"])

check = orders.merge(
    stores[["store_id", "opening_date"]],
    on="store_id"
)

invalid = check[
    check["order_date"] < check["opening_date"]
]

print("Orders before store opening:", len(invalid))

Orders before store opening: 0